dim swApp
dim storePath
dim sw2003api
dim sw2007api
dim docVisible
#If VBA7 Then
Private Type BROWSEINFO
   hwndOwner       As LongPtr
   pIDLRoot        As Long
   pszDisplayName  As String
   lpszTitle       As String
   ulFlags         As Long
   lpfnCallback    As LongPtr
   lParam          As LongPtr
  iImage          As Long
End Type
Private Declare PtrSafe Function SHBrowseForFolder Lib "Shell32" (lpbi As BROWSEINFO) As Long
Private Declare PtrSafe Function SHGetPathFromIDList Lib "Shell32" (ByVal pidList As Long, ByVal lpBuffer As String) As Long
Private Declare PtrSafe Sub CoTaskMemFree Lib "ole32" (ByVal hMem As Long)
#Else
Private Type BROWSEINFO
   hwndOwner       As Long
   pIDLRoot        As Long
   pszDisplayName  As Long
   lpszTitle       As String
   ulFlags         As Long
   lpfnCallback    As Long
   lParam          As Long
  iImage          As Long
End Type
Private Declare Function SHBrowseForFolder Lib "Shell32" (lpbi As BROWSEINFO) As Long
Private Declare Function SHGetPathFromIDList Lib "Shell32" (ByVal pidList As Long, ByVal lpBuffer As String) As Long
Private Declare Sub CoTaskMemFree Lib "ole32" (ByVal hMem As Long)
#End If
Private Const MAX_PATH = 260
'Directories only
Private Const BIF_RETURNONLYFSDIRS = &H1&
'Windows 2000 (Shell32.dll 5.0) extended dialog
Private Const BIF_NEWDIALOGSTYLE = &H40
' show edit box
Private Const BIF_EDITBOX = &H10&
Function getFeatureByTypeOcc(model, typ, nr)  
  Set feat = model.FirstFeature ' Get the 1st feature in part
  Set res = Nothing
  Count = 0
  Do While Not feat Is Nothing ' While we have a valid feature
    If feat.GetTypeName() = typ Then
      Count = Count + 1
      If Count = nr Then
        Set res = feat
        Exit Do
      End If
    End If
    Set feat = feat.GetNextFeature() ' Get the next feature
  Loop ' Continue until no more
  Set getFeatureByTypeOcc = res
End Function
Function getLastFeatureByType(model,typ)  
  Set feat = model.FirstFeature ' Get the 1st feature in part
  Set res = Nothing
  Count = 0
  Do While Not feat Is Nothing ' While we have a valid feature
    If feat.GetTypeName() = typ Then
      Set res = feat
    End If
    Set feat = feat.GetNextFeature() ' Get the next feature
  Loop ' Continue until no more
  Set getLastFeatureByType = res
End Function
' this code with copy a matrix to a other
Function copyMat4x4(source)
Dim res(0 To 15) As Double
For i = 0 To 15
 res(i) = source(i)
Next
copyMat4x4 = res
End Function

' This code creates a mat from a sw mat
Function createMatFromSWMat(source)
 Dim res(0 To 15) As Double
 res(0) = source(0)
 res(1) = source(1)
 res(2) = source(2)
 res(3) = 0
 res(4) = source(3)
 res(5) = source(4)
 res(6) = source(5)
 res(7) = 0
 res(8) = source(6)
 res(9) = source(7)
 res(10) = source(8)
 res(11) = 0
 res(12) = source(9)
 res(13) = source(10)
 res(14) = source(11)
 res(15) = source(12)
 createMatFromSWMat = res
End Function
Function createSWMatFromMat(source)
 Dim res(0 To 15) As Double
 res(0) = source(0)
 res(1) = source(1)
 res(2) = source(2)
 res(3) = source(4)
 res(4) = source(5)
 res(5) = source(6)
 res(6) = source(8)
 res(7) = source(9)
 res(8) = source(10)
 res(9) = source(12)
 res(10) = source(13)
 res(11) = source(14)
 res(12) = source(15)
 res(13) = 0
 res(14) = 0
 res(15) = 0
 createSWMatFromMat = res
End Function
Function createMat4x4FromValues(x1,x2,x3,y1,y2,y3,z1,z2,z3,t1,t2,t3)
 Dim res(0 To 15) As Double
 res(0) = x1
 res(1) = x2
 res(2) = x3
 res(3) = 0
 res(4) = y1
 res(5) = y2
 res(6) = y3
 res(7) = 0
 res(8) = z1
 res(9) = z2
 res(10) =z3
 res(11) = 0
 res(12) = t1
 res(13) = t2
 res(14) = t3
 res(15) = 1
 createMat4x4FromValues = res
End Function
' this code will mult a common mat with any other stuff
Function multMatMat(ld, xld, yld, rd, xrd, yrd)
  mulRes = yld * xrd
  'Dim od(0 To 0) As Variant
  ReDim od(mulRes - 1) As Double
  For i = 0 To mulRes - 1
   od(i) = 0#
  Next
  y = 0
  While y < yld
    x = 0
    While x < xrd
      i = 0
      While i < xld
       od(x * yld + y) = od(x * yld + y) + ld(i * yld + y) * rd(x * yrd + i)
       i = i + 1
      Wend
      x = x + 1
    Wend
    y = y + 1
  Wend
  multMatMat = od

End Function
' this code will mult a vector with a matrix
Function mulMat4x4Values3d(mat, x,y,z)
  tmp = createVec4d(x, y, z, 1)
  res = multMatMat(mat, 4, 4, tmp, 1, 3)
  mulMat4x4Values3d = createVec3d(res(0), res(1), res(2))
End Function
Function mulMat4x4Vec3d(mat, vec)
  tmp = createVec4d(vec(0), vec(1), vec(2), 1)
  res = multMatMat(mat, 4, 4, tmp, 1, 3)
  mulMat4x4Vec3d = createVec3d(res(0), res(1), res(2))
End Function
Function mulMat4x4Mat4x4(mat1, mat2)
  mulMat4x4Mat4x4 = multMatMat(mat1, 4, 4, mat2, 4, 4)
End Function
' create a 4x4 matrix
Function createMat4x4()
 Dim res(0 To 15) As Double
 for i = 0 to 15 
 res(i) = 0
 next
 createMat4x4 = res
End Function
Function createMat4x4Ident()
 Dim res(0 To 15) As Double
 res(0) = 1
 res(5) = 1
 res(10) = 1
 res(15) = 1
 res(1) = 0
 res(2) = 0
 res(3) = 0
 res(4) = 0
 res(6) = 0
 res(7) = 0
 res(8) = 0
 res(9) = 0
 res(11) = 0
 res(12) = 0
 res(13) = 0
 res(14) = 0
 createMat4x4Ident = res
End Function
' this function create a new vector
Function createVec3d(x, y, z)
 Dim res(0 To 2) As Double
 res(0) = x
 res(1) = y
 res(2) = z
 createVec3d = res
End Function
' this function create a new vector
Function createVec4d(x, y, z, w)
 Dim res(0 To 3) As Double
 res(0) = x
 res(1) = y
 res(2) = z
 res(3) = w
 createVec4d = res
End Function

Function getMatTVec(mat)
 getMatTVec = createVec3d(mat(12), mat(13), mat(14))
End Function

Sub setMatTVec(mat, v)
 mat(12) = v(0)
 mat(13) = v(1)
 mat(14) = v(2)
End Sub
Sub setMatXVec(mat, v)
 mat(0) = v(0)
 mat(1) = v(1)
 mat(2) = v(2)
End Sub
Sub setMatYVec(mat, v)
 mat(4) = v(0)
 mat(5) = v(1)
 mat(6) = v(2)
End Sub
Sub setMatZVec(mat, v)
 mat(8) = v(0)
 mat(9) = v(1)
 mat(10) = v(2)
End Sub
Sub setMatScale(mat, s)
 mat(15) = s
End Sub
Function getMatXVec(mat)
 getMatXVec = createVec3d(mat(0), mat(1), mat(2))
End Function
Function getMatYVec(mat)
 getMatYVec = createVec3d(mat(4), mat(5), mat(6))
End Function
Function getMatZVec(mat)
 getMatZVec = createVec3d(mat(8), mat(9), mat(10))
End Function

Function negVec3d(v)
 negVec3d = createVec3d(-v(0), -v(1), -v(2))
End Function
Function scaleVec3d(v,s)
 scaleVec3d = createVec3d(v(0)*s,v(1)*s,v(2)*s)
End Function
' invert a 4x4 matrix
Function invMat4x4(source)
target = copyMat4x4(source)
setMatTVec target, createVec3d(0, 0, 0)
 target(1) = source(4)
 target(4) = source(1)
 target(2) = source(8)
 target(8) = source(2)
 target(6) = source(9)
 target(9) = source(6)
 setMatScale target,1
 t = getMatTVec(source)
 v = mulMat4x4Vec3d(target, t)
 setMatTVec target, negVec3d(v)
 invMat4x4 = target
End Function
Function getFaceFromModel(part, pos, normal)
 Dim partBodies As Variant
 partBodies = part.GetBodies(swSolidBody)
 For k = LBound(partBodies) To UBound(partBodies)
   found = 0
   Dim body As Object
   Set body = partBodies(k)
   Set face = body.GetFirstFace()
   getFaceFromModel = noting
   Do While Not face Is Nothing ' While we have a valid feature
     Set sur = face.GetSurface()
     If sur.IsPlane() Then
       planePara = sur.PlaneParams
       faceNormal = face.normal
       nTest = faceNormal(0) * normal(0) + faceNormal(1) * normal(1) + faceNormal(2) * normal(2)
       If nTest > 1 - 0.000001 Then
         ' check projection
         closeRes = face.GetClosestPointOn(pos(0), pos(1), pos(2))
         dTest = (pos(0) - closeRes(0)) * (pos(0) - closeRes(0)) + (pos(1) - closeRes(1)) * (pos(1) - closeRes(1)) + (pos(2) - closeRes(2)) * (pos(2) - closeRes(2))
         If dTest < 0.000001 Then
           Set getFaceFromModel = face
           found=1
           Exit Do
         End If
       End If
     else
       If sur.IsCylinder() then
         closeRes = face.GetClosestPointOn(pos(0), pos(1), pos(2))
         dTest = (pos(0) - closeRes(0)) * (pos(0) - closeRes(0)) + (pos(1) - closeRes(1)) * (pos(1) - closeRes(1)) + (pos(2) - closeRes(2)) * (pos(2) - closeRes(2))
         If dTest < 0.00000001 Then
           res=sur.EvaluateAtPoint(closeRes(0),closeRes(1),closeRes(2))
           nTest=res(0)*normal(0)+res(1)*normal(1)+res(2)*normal(2)
           if nTest>1-0.00000001 then
             Set getFaceFromModel = face
             found=1
             Exit Do
           End if
         End if
       End if
     End if
     Set face = face.GetNextFace ' Get the next Face
   Loop
   If (found = 1) Then
     Exit For
   End If
 Next k
End Function
Function getEdgeFromModel(part, pos,byref edgeRet)
 Dim partBodies As Variant
 partBodies = part.GetBodies(swSolidBody)
 For k = LBound(partBodies) To UBound(partBodies)
   Dim body As Object
   Set body = partBodies(k)
   edges= body.GetEdges()
   start= LBound(edges)
   ende = UBound(edges)
   For i = start To ende
     Set edge = edges(i)
     closeRes=edge.GetClosestPointOn(pos(0),pos(1),pos(2))
     dTest = (pos(0) - closeRes(0)) * (pos(0) - closeRes(0)) + (pos(1) - closeRes(1)) * (pos(1) - closeRes(1)) + (pos(2) - closeRes(2)) * (pos(2) - closeRes(2))
     If dTest < 0.00000001 Then
       set edgeRet=edge
       getEdgeFromModel=true
       exit function
     End If
   Next i
 Next k
 getEdgeFromModel=false
End Function
sub cLn(part,wMat,x1,y1,x2,y2)
pk1=mulMat4x4Values3d(wMat,x1,y1,0)
pk2=mulMat4x4Values3d(wMat,x2,y2,0)
Part.CreateLine2 pk1(0),pk1(1),0,pk2(0),pk2(1),0
end sub
sub cCLn(part,wMat,x1,y1,x2,y2)
pk1=mulMat4x4Values3d(wMat,x1,y1,0)
pk2=mulMat4x4Values3d(wMat,x2,y2,0)
Part.CreateCenterLineVB pk1(0),pk1(1),0,pk2(0),pk2(1),0
end sub
sub cArc(part,wMat,x1,y1,x2,y2,x3,y3)
pk1=mulMat4x4Values3d(wMat,x1,y1,0)
pk2=mulMat4x4Values3d(wMat,x2,y2,0)
pk3=mulMat4x4Values3d(wMat,x3,y3,0)
Part.Create3PointArc pk1(0),pk1(1),0,pk3(0),pk3(1),0,pk2(0),pk2(1),0
end sub
sub cCir(part,wMat,x1,y1,rad)
pk1=mulMat4x4Values3d(wMat,x1,y1,0)
Part.CreateCircleByRadius2 pk1(0),pk1(1),0,rad
end sub
Public Function BrowseForFolder() As String
  Dim tBI         As BROWSEINFO
  Dim lngPIDL     As Long
  Dim strPath     As String
  With tBI
    .lpszTitle = ""
    .ulFlags = BIF_RETURNONLYFSDIRS Or BIF_NEWDIALOGSTYLE Or BIF_EDITBOX
  End With
  lngPIDL = SHBrowseForFolder(tBI)
  If (lngPIDL <> 0) Then
    ' get path from ID list
    strPath = Space$(MAX_PATH)
    SHGetPathFromIDList lngPIDL, strPath
    strPath = Left$(strPath, InStr(strPath, Chr$(0)) - 1)
    ' release list
    CoTaskMemFree lngPIDL
  End If
  BrowseForFolder = strPath
End Function
Sub CreatePart0
dim error as long
set res=swApp.OpenDoc2 ( storePath & "170_5-PC(F,D-231-1)0000_0_dummy.sldprt",1,true,false,true,error)
if not res is nothing then
 exit sub
end if
set part=swApp.NewPart
part.SetAddToDB(true)
part.SetDisplayWhenAdded (false)
part.SetUnits 3,2,64,5,false
part.AddCustomInfo3 "", "NN", 30, "Standard Air Cylinder_dummy"
part.AddCustomInfo3 "", "NT", 30, "Original Line - Standard Air Cylinders"
part.AddCustomInfo3 "", "NB", 30, "170.5-PC(F,D-231-1)0000_0_dummy"
part.AddCustomInfo3 "", "NBSYN", 30, "$PN.$COLOR.$FNUT._$STRED._dummy"
part.AddCustomInfo3 "", "LINA", 30, "170.5-PC(F,D-231-1)0000_0_dummy"
part.AddCustomInfo3 "", "PN", 30, "170.5-PC(F,D-231-1)00"
part.AddCustomInfo3 "", "BORE", 30, "1 1/2"
part.AddCustomInfo3 "", "BOREPN", 30, "17"
part.AddCustomInfo3 "", "STROKE", 30, "0.500"
part.AddCustomInfo3 "", "ACTING", 30, "Single"
part.AddCustomInfo3 "", "MNT", 30, "Rear Pivot Mounting"
part.AddCustomInfo3 "", "DER", 30, "N/A"
part.AddCustomInfo3 "", "NR", 30, "Standard"
part.AddCustomInfo3 "", "BM", 30, "N/A"
part.AddCustomInfo3 "", "CO", 30, "N/A"
part.AddCustomInfo3 "", "OO", 30, "N/A"
part.AddCustomInfo3 "", "VO", 30, "N/A"
part.AddCustomInfo3 "", "M", 30, "Without Magnet"
part.AddCustomInfo3 "", "EE", 30, "Without Extra Extension"
part.AddCustomInfo3 "", "EEL", 30, "0.000"
part.AddCustomInfo3 "", "K", 30, "Standard"
part.AddCustomInfo3 "", "Q", 30, "Without Side Ported Rear Head"
part.AddCustomInfo3 "", "Y", 30, "Without Pivot Bushing"
part.AddCustomInfo3 "", "F", 30, "Standard"
part.AddCustomInfo3 "", "G", 30, "Without Magnalube Lubrication"
part.AddCustomInfo3 "", "T", 30, "Standard"
part.AddCustomInfo3 "", "B", 30, "Without Bumper"
part.AddCustomInfo3 "", "H", 30, "Standard"
part.AddCustomInfo3 "", "SER", 30, "N/A"
part.AddCustomInfo3 "", "SR", 30, "Carbon Steel Rod"
part.AddCustomInfo3 "", "NT", 30, "Standard"
part.AddCustomInfo3 "", "W", 30, "N/A"
part.AddCustomInfo3 "", "E", 30, "Without Special Lube and Seals"
part.AddCustomInfo3 "", "HL", 30, "N/A"
part.AddCustomInfo3 "", "STPT1", 30, "N/A"
part.AddCustomInfo3 "", "STPT2", 30, "N/A"
part.AddCustomInfo3 "", "STPT3", 30, "N/A"
part.AddCustomInfo3 "", "STPT4", 30, "N/A"
part.AddCustomInfo3 "", "MB", 30, "Without Mounting Bracket"
part.AddCustomInfo3 "", "PB", 30, "Without Pivot Bracket"
part.AddCustomInfo3 "", "PRC", 30, "D-231-1 (front)"
part.AddCustomInfo3 "", "TB", 30, "N/A"
part.AddCustomInfo3 "", "MN", 30, "Without Mounting Nut"
part.AddCustomInfo3 "", "COLOR", 30, "0"
part.AddCustomInfo3 "", "A1N", 30, "1.3120"
part.AddCustomInfo3 "", "A1P", 30, "1.8750"
part.AddCustomInfo3 "", "A1B", 30, "2.3750"
part.AddCustomInfo3 "", "A4N", 30, "0.5000"
part.AddCustomInfo3 "", "A4P", 30, "0.2525"
part.AddCustomInfo3 "", "A5", 30, "0.0400"
part.AddCustomInfo3 "", "A1NH", 30, "0.6880"
part.AddCustomInfo3 "", "A1PH", 30, "1.7500"
part.AddCustomInfo3 "", "A1BH", 30, "1.3750"
part.AddCustomInfo3 "", "A1SH", 30, "1.5000"
part.AddCustomInfo3 "", "A2NH", 30, "0.2500"
part.AddCustomInfo3 "", "A13", 30, "1.3750"
part.AddCustomInfo3 "", "G5", 30, "0.0000"
part.AddCustomInfo3 "", "S1", 30, "1.7500"
part.AddCustomInfo3 "", "D1N", 30, "1.5565"
part.AddCustomInfo3 "", "D1B", 30, "1.5565"
part.AddCustomInfo3 "", "D1P", 30, "1.5800"
part.AddCustomInfo3 "", "D1NRH", 30, "1.5565"
part.AddCustomInfo3 "", "D1PRH", 30, "1.5565"
part.AddCustomInfo3 "", "D1BRH", 30, "1.5800"
part.AddCustomInfo3 "", "XT2", 30, "0.5000"
part.AddCustomInfo3 "", "CUSHF", 30, "0"
part.AddCustomInfo3 "", "CUSHR", 30, "0"
part.AddCustomInfo3 "", "BUSHCON", 30, "D-5775"
part.AddCustomInfo3 "", "CSCON", 30, "D-32391-SS"
part.AddCustomInfo3 "", "FNUT", 30, "0"
part.AddCustomInfo3 "", "STRED", 30, "0.000"
part.AddCustomInfo3 "", "ROD", 30, "Rod"
part.AddCustomInfo3 "", "A2N", 30, "0.62500"
part.AddCustomInfo3 "", "A2P", 30, "0.62500"
part.AddCustomInfo3 "", "SUPPLIER", 30, "BIMBA"
part.AddCustomInfo3 "", "ARTICLENO", 30, "170.5-PC(F,D-231-1)0000_0_dummy"
part.AddCustomInfo3 "", "BOMINFO", 30, "170.5-PC(F,D-231-1)0000_0_dummy"
part.AddCustomInfo3 "", "CREATOR", 30, "CADENAS GmbH"
part.AddCustomInfo3 "", "IsFastener", 30, "0"
part.SummaryInfo(0)="170.5-PC(F,D-231-1)0000_0_dummy"
part.SummaryInfo(4)="Original Line - Standard Air Cylinders"
part.SummaryInfo(2)="Cadenas PARTsolutions"
valRGB=part.MaterialPropertyValues
valRGB(0)=0.75294119119644
valRGB(1)=0.75294119119644
valRGB(2)=0.75294119119644
part.MaterialPropertyValues=valRGB
Dim featMgr as object
if (sw2003api=1) then
  set featMgr=part.FeatureManager
End If
part.SetDisplayWhenAdded (true)
part.SetAddToDB(false)
part.EditRebuild3
part.Rebuild swRebuildAll
part.SaveAs2 storePath & "170_5-PC(F,D-231-1)0000_0_dummy.sldprt",0,0,false
End Sub
Sub CreatePart1
dim error as long
set res=swApp.OpenDoc2 ( storePath & "17000-0_rod_guide.sldprt",1,true,false,true,error)
if not res is nothing then
 exit sub
end if
set part=swApp.NewPart
part.SetAddToDB(true)
part.SetDisplayWhenAdded (false)
part.SetUnits 3,2,64,5,false
part.AddCustomInfo3 "", "NN", 30, "Rod Guide"
part.AddCustomInfo3 "", "NT", 30, "Original Line - Standard Air Cylinders"
part.AddCustomInfo3 "", "NB", 30, "17000-0_rod_guide"
part.AddCustomInfo3 "", "NBSYN", 30, "$PN.-$RODTRANS._rod_guide"
part.AddCustomInfo3 "", "LINA", 30, "17000-0_rod_guide"
part.AddCustomInfo3 "", "BORE", 30, "1 1/2"
part.AddCustomInfo3 "", "BOREPN", 30, "17"
part.AddCustomInfo3 "", "MNT", 30, "Front Nose"
part.AddCustomInfo3 "", "MNTALG", 30, "\'\' , \'Front Nose\' , \'BF\' , \'Front Block\' , \'BFT\' , \'Front Trunnion\' , \'A\' , \'Adjustable Stroke\',\'BR\' , \'Rear Block\'"
part.AddCustomInfo3 "", "ACTING", 30, "Single Acting"
part.AddCustomInfo3 "", "NR", 30, "Without Non-rotating Rod"
part.AddCustomInfo3 "", "K", 30, "Standard"
part.AddCustomInfo3 "", "Q", 30, "Without Side Ported Rear Head"
part.AddCustomInfo3 "", "T1", 30, "without T1"
part.AddCustomInfo3 "", "T2", 30, "without T2"
part.AddCustomInfo3 "", "T3", 30, "without T3"
part.AddCustomInfo3 "", "T4", 30, "without T4"
part.AddCustomInfo3 "", "MB", 30, "0"
part.AddCustomInfo3 "", "A1N", 30, "1.3120"
part.AddCustomInfo3 "", "A1P", 30, "1.8750"
part.AddCustomInfo3 "", "A1B", 30, "2.3750"
part.AddCustomInfo3 "", "A2N", 30, "0.6250"
part.AddCustomInfo3 "", "A2P", 30, "0.6250"
part.AddCustomInfo3 "", "A3N", 30, "0.1880"
part.AddCustomInfo3 "", "A3P", 30, "1.0000"
part.AddCustomInfo3 "", "A4N", 30, "0.5000"
part.AddCustomInfo3 "", "A4P", 30, "0.2525"
part.AddCustomInfo3 "", "A5", 30, "0.0400"
part.AddCustomInfo3 "", "A6N", 30, "0.2500"
part.AddCustomInfo3 "", "A6P", 30, "0.0000"
part.AddCustomInfo3 "", "A7N", 30, "0.6430"
part.AddCustomInfo3 "", "A7P", 30, "0.2500"
part.AddCustomInfo3 "", "A8N", 30, "0.0300"
part.AddCustomInfo3 "", "A8NR", 30, "0.0300"
part.AddCustomInfo3 "", "D1N", 30, "1.5565"
part.AddCustomInfo3 "", "D1P", 30, "1.5565"
part.AddCustomInfo3 "", "D1B", 30, "1.5800"
part.AddCustomInfo3 "", "D2", 30, "1.5115"
part.AddCustomInfo3 "", "D3N", 30, "0.8120"
part.AddCustomInfo3 "", "D3P", 30, "0.0000"
part.AddCustomInfo3 "", "D4N", 30, "0.4730"
part.AddCustomInfo3 "", "D4P", 30, "0.9690"
part.AddCustomInfo3 "", "D4NR", 30, "0.4395"
part.AddCustomInfo3 "", "D5N", 30, "0.4420"
part.AddCustomInfo3 "", "D5NR", 30, "0.4395"
part.AddCustomInfo3 "", "C1", 30, "0.030"
part.AddCustomInfo3 "", "C2N", 30, "0.0300"
part.AddCustomInfo3 "", "C2P", 30, "0.0300"
part.AddCustomInfo3 "", "C3N", 30, "0.0000"
part.AddCustomInfo3 "", "C3P", 30, "0.0000"
part.AddCustomInfo3 "", "C4N", 30, "0.0000"
part.AddCustomInfo3 "", "C4P", 30, "0.0300"
part.AddCustomInfo3 "", "NDMN", 30, "0.7500"
part.AddCustomInfo3 "", "NDMP", 30, "0.7500"
part.AddCustomInfo3 "", "TAB", 30, "UNF"
part.AddCustomInfo3 "", "D6N", 30, "0.7475"
part.AddCustomInfo3 "", "D6P", 30, "0.7475"
part.AddCustomInfo3 "", "A9N", 30, "0.0940"
part.AddCustomInfo3 "", "A9P", 30, "0.0940"
part.AddCustomInfo3 "", "D7N", 30, "0.6535"
part.AddCustomInfo3 "", "D7P", 30, "0.6535"
part.AddCustomInfo3 "", "A10N", 30, "0.0965"
part.AddCustomInfo3 "", "A10P", 30, "0.0965"
part.AddCustomInfo3 "", "R1N", 30, "0.0440"
part.AddCustomInfo3 "", "R1P", 30, "0.0440"
part.AddCustomInfo3 "", "D8", 30, "0.8120"
part.AddCustomInfo3 "", "D9", 30, "0.7500"
part.AddCustomInfo3 "", "D10", 30, "0.6880"
part.AddCustomInfo3 "", "A11", 30, "0.8650"
part.AddCustomInfo3 "", "A12", 30, "0.9590"
part.AddCustomInfo3 "", "A13", 30, "1.1150"
part.AddCustomInfo3 "", "A14N", 30, "0.6250"
part.AddCustomInfo3 "", "A14B", 30, "0.7190"
part.AddCustomInfo3 "", "D11N", 30, "0.2500"
part.AddCustomInfo3 "", "NDM2N", 30, "0.4050"
part.AddCustomInfo3 "", "NDM2DP", 30, "0.4200"
part.AddCustomInfo3 "", "HEXN", 30, "0.4375"
part.AddCustomInfo3 "", "S1", 30, "1.7500"
part.AddCustomInfo3 "", "B1", 30, "0.1275"
part.AddCustomInfo3 "", "B2", 30, "1.0050"
part.AddCustomInfo3 "", "B22", 30, "0.0000"
part.AddCustomInfo3 "", "DB", 30, "0.0000"
part.AddCustomInfo3 "", "B3", 30, "0.6200"
part.AddCustomInfo3 "", "B4", 30, "1.1300"
part.AddCustomInfo3 "", "X1", 30, "0.1230"
part.AddCustomInfo3 "", "X2", 30, "0.9975"
part.AddCustomInfo3 "", "NDM3", 30, "0.3125"
part.AddCustomInfo3 "", "NDM4", 30, "0.2500"
part.AddCustomInfo3 "", "NDM4DP", 30, "0.4950"
part.AddCustomInfo3 "", "DD", 30, "1.7500"
part.AddCustomInfo3 "", "CB", 30, "0.3750"
part.AddCustomInfo3 "", "CBDP", 30, "0.2500"
part.AddCustomInfo3 "", "XTX", 30, "1.0610"
part.AddCustomInfo3 "", "XT1", 30, "0.5000"
part.AddCustomInfo3 "", "XT2", 30, "0.3800"
part.AddCustomInfo3 "", "NDMH", 30, "0.7500"
part.AddCustomInfo3 "", "TRIM", 30, "0"
part.AddCustomInfo3 "", "C11", 30, "0.3965"
part.AddCustomInfo3 "", "C22", 30, "0.5625"
part.AddCustomInfo3 "", "C33", 30, "0.3050"
part.AddCustomInfo3 "", "C44", 30, "0.6250"
part.AddCustomInfo3 "", "C55", 30, "0.8750"
part.AddCustomInfo3 "", "CD1", 30, "0.2650"
part.AddCustomInfo3 "", "CD2", 30, "0.1980"
part.AddCustomInfo3 "", "CD3", 30, "0.1345"
part.AddCustomInfo3 "", "CNDM3", 30, "0.2500"
part.AddCustomInfo3 "", "CTAB3", 30, "UNS"
part.AddCustomInfo3 "", "CUSH", 30, "0"
part.AddCustomInfo3 "", "LCD", 30, "0.0000"
part.AddCustomInfo3 "", "RODTRANS", 30, "0.00000"
part.AddCustomInfo3 "", "SUPPLIER", 30, "BIMBA"
part.AddCustomInfo3 "", "ARTICLENO", 30, "17000-0_rod_guide"
part.AddCustomInfo3 "", "BOMINFO", 30, "17000-0_rod_guide"
part.AddCustomInfo3 "", "CREATOR", 30, "CADENAS GmbH"
part.AddCustomInfo3 "", "IsFastener", 30, "0"
part.SummaryInfo(0)="17000-0_rod_guide"
part.SummaryInfo(4)="Original Line - Standard Air Cylinders"
part.SummaryInfo(2)="Cadenas PARTsolutions"
valRGB=part.MaterialPropertyValues
valRGB(0)=0.82745099067688
valRGB(1)=0.82745099067688
valRGB(2)=0.82745099067688
part.MaterialPropertyValues=valRGB
Dim featMgr as object
if (sw2003api=1) then
  set featMgr=part.FeatureManager
End If
part.CreatePlaneFixed createVec3d(0,0,0),createVec3d(1,0,0),createVec3d(0,1,0),1
part.BlankRefGeom
set feat4=getLastFeatureByType(part,"RefPlane")
feat4.select false
codeBag0 part
set feat4=getLastFeatureByType(part,"ProfileFeature")
feat4.select false
if (sw2003api=0) then
  part.FeatureRevolve2 6.2831853071796,1,6.2831853071796,0,0
else
  featMgr.FeatureRevolve 6.2831853071796,1,6.2831853071796,0,0,1,1,1
end if
if sw2003api=1 then
  if getEdgeFromModel(part,createVec3d(0.00093599,-0.009525,0),cylEdge) then
    cylEdge.Select(false)
    Part.InsertCosmeticThread 0,0.01717802,0.010246037461346,""
  elseif getEdgeFromModel(part,createVec3d(0.0093100474613459,-0.009525,0),cylEdge) then
    cylEdge.Select(false)
    Part.InsertCosmeticThread 0,0.01717802,0.010246037461346,""
  End If
End If
part.CreatePlaneFixed createVec3d(0,0,0),createVec3d(1,0,0),createVec3d(0,1,0),1
part.BlankRefGeom
set feat6=getLastFeatureByType(part,"RefPlane")
feat6.select false
codeBag1 part
set feat6=getLastFeatureByType(part,"ProfileFeature")
feat6.select false
if (sw2003api=0) then
  part.FeatureRevolve2 6.2831853071796,1,6.2831853071796,0,0
else
  featMgr.FeatureRevolve 6.2831853071796,1,6.2831853071796,0,0,1,1,1
end if
part.CreatePlaneFixed createVec3d(0,0,0),createVec3d(1,0,0),createVec3d(0,1,0),1
part.BlankRefGeom
set feat8=getLastFeatureByType(part,"RefPlane")
feat8.select false
codeBag2 part
set feat8=getLastFeatureByType(part,"ProfileFeature")
feat8.select false
if (sw2003api=0) then
  part.FeatureRevolve2 6.2831853071796,1,6.2831853071796,0,0
else
  featMgr.FeatureRevolve 6.2831853071796,1,6.2831853071796,0,0,1,1,1
end if
part.CreatePlaneFixed createVec3d(0,0,0),createVec3d(1,0,0),createVec3d(0,1,0),1
part.BlankRefGeom
set feat10=getLastFeatureByType(part,"RefPlane")
feat10.select false
codeBag3 part
set feat10=getLastFeatureByType(part,"ProfileFeature")
feat10.select false
if (sw2003api=0) then
  part.FeatureRevolveCut2 6.2831853071796,1,6.2831853071796,0,0
else
  featMgr.FeatureRevolveCut 6.2831853071796,1,6.2831853071796,0,0,1,1
end if
part.CreatePlaneFixed createVec3d(0,0,0),createVec3d(1,0,0),createVec3d(0,1,0),1
part.BlankRefGeom
set feat19=getLastFeatureByType(part,"RefPlane")
feat19.select false
codeBag4 part
set feat19=getLastFeatureByType(part,"ProfileFeature")
feat19.select false
if (sw2003api=0) then
  part.FeatureRevolve2 6.2831853071796,1,6.2831853071796,0,0
else
  featMgr.FeatureRevolve 6.2831853071796,1,6.2831853071796,0,0,1,1,1
end if
part.SetDisplayWhenAdded (true)
part.SetAddToDB(false)
part.EditRebuild3
part.Rebuild swRebuildAll
part.SaveAs2 storePath & "17000-0_rod_guide.sldprt",0,0,false
End Sub
Sub CreatePart2
dim error as long
set res=swApp.OpenDoc2 ( storePath & "17-2_0432C.sldprt",1,true,false,true,error)
if not res is nothing then
 exit sub
end if
set part=swApp.NewPart
part.SetAddToDB(true)
part.SetDisplayWhenAdded (false)
part.SetUnits 3,2,64,5,false
part.AddCustomInfo3 "", "NN", 30, "Tube"
part.AddCustomInfo3 "", "NT", 30, "Original Line - Standard Air Cylinders"
part.AddCustomInfo3 "", "NB", 30, "17-2.0432C"
part.AddCustomInfo3 "", "NBSYN", 30, "$PN."
part.AddCustomInfo3 "", "LINA", 30, "17-2.0432C"
part.AddCustomInfo3 "", "BORE", 30, "1 1/2"
part.AddCustomInfo3 "", "BOREPN", 30, "17"
part.AddCustomInfo3 "", "MNT", 30, "Front Nose"
part.AddCustomInfo3 "", "MNTALG", 30, "\'\' , \'Front Nose\' , \'BF\' , \'Front Block\' , \'BFT\' , \'Front Trunnion\' , \'A\' , \'Adjustable Stroke\'"
part.AddCustomInfo3 "", "ACTING", 30, "Single Acting"
part.AddCustomInfo3 "", "NR", 30, "Without Non-rotating Rod"
part.AddCustomInfo3 "", "L", 30, "2.0430"
part.AddCustomInfo3 "", "ODN", 30, "1.5565"
part.AddCustomInfo3 "", "ODP", 30, "1.5565"
part.AddCustomInfo3 "", "ODB", 30, "1.5800"
part.AddCustomInfo3 "", "ID", 30, "1.5115"
part.AddCustomInfo3 "", "DV", 30, "0.00000000"
part.AddCustomInfo3 "", "LV", 30, "0.00000000"
part.AddCustomInfo3 "", "LV1", 30, "0.00000000"
part.AddCustomInfo3 "", "G", 30, "0.0400"
part.AddCustomInfo3 "", "FOURHOLES", 30, "2"
part.AddCustomInfo3 "", "AA", 30, "0.3750"
part.AddCustomInfo3 "", "BB", 30, "0.1250"
part.AddCustomInfo3 "", "SR", 30, "Carbon Steel Rod"
part.AddCustomInfo3 "", "SUPPLIER", 30, "BIMBA"
part.AddCustomInfo3 "", "ARTICLENO", 30, "17-2.0432C"
part.AddCustomInfo3 "", "BOMINFO", 30, "17-2.0432C"
part.AddCustomInfo3 "", "CREATOR", 30, "CADENAS GmbH"
part.AddCustomInfo3 "", "IsFastener", 30, "0"
part.SummaryInfo(0)="17-2.0432C"
part.SummaryInfo(4)="Original Line - Standard Air Cylinders"
part.SummaryInfo(2)="Cadenas PARTsolutions"
valRGB=part.MaterialPropertyValues
valRGB(0)=0.70588237047195
valRGB(1)=0.70588237047195
valRGB(2)=0.70588237047195
part.MaterialPropertyValues=valRGB
Dim featMgr as object
if (sw2003api=1) then
  set featMgr=part.FeatureManager
End If
part.CreatePlaneFixed createVec3d(0,0,0),createVec3d(1,0,0),createVec3d(0,1,0),1
part.BlankRefGeom
set feat5=getLastFeatureByType(part,"RefPlane")
feat5.select false
codeBag5 part
set feat5=getLastFeatureByType(part,"ProfileFeature")
feat5.select false
if (sw2003api=0) then
  part.FeatureRevolve2 6.2831853071796,1,6.2831853071796,0,0
else
  featMgr.FeatureRevolve 6.2831853071796,1,6.2831853071796,0,0,1,1,1
end if
part.CreatePlaneFixed createVec3d(0,0,0),createVec3d(1,0,0),createVec3d(0,1,0),1
part.BlankRefGeom
set feat7=getLastFeatureByType(part,"RefPlane")
feat7.select false
codeBag6 part
set feat7=getLastFeatureByType(part,"ProfileFeature")
feat7.select false
if (sw2003api=0) then
  part.FeatureCut 1,0,1,0,0,0.01976755,0.01976755,1,1,0,0,0,0,0,0
else
  featMgr.FeatureCut 1,0,1,0,0,0.01976755,0.01976755,1,1,0,0,0,0,0,0,0,0,0,1,1
end if
part.SetDisplayWhenAdded (true)
part.SetAddToDB(false)
part.EditRebuild3
part.Rebuild swRebuildAll
part.SaveAs2 storePath & "17-2_0432C.sldprt",0,0,false
End Sub
Sub CreatePart3
dim error as long
set res=swApp.OpenDoc2 ( storePath & "17P0000_rear_head.sldprt",1,true,false,true,error)
if not res is nothing then
 exit sub
end if
set part=swApp.NewPart
part.SetAddToDB(true)
part.SetDisplayWhenAdded (false)
part.SetUnits 3,2,64,5,false
part.AddCustomInfo3 "", "NN", 30, "Rear Head"
part.AddCustomInfo3 "", "NT", 30, "Original Line - Standard Air Cylinders"
part.AddCustomInfo3 "", "NB", 30, "17P0000_rear_head"
part.AddCustomInfo3 "", "NBSYN", 30, "$PN._rear_head"
part.AddCustomInfo3 "", "LINA", 30, "17P0000_rear_head"
part.AddCustomInfo3 "", "PN", 30, "17P0000"
part.AddCustomInfo3 "", "BORE", 30, "1.50000"
part.AddCustomInfo3 "", "BOREPN", 30, "17"
part.AddCustomInfo3 "", "MNT", 30, "Rear Pivot"
part.AddCustomInfo3 "", "MNTALG", 30, "\'\' , \'Front Nose\' , \'P\' , \'Rear Pivot\' , \'S\' , \'Built-in Valve S\' , \'DX\' , \'Double End\' , \'A\' , \'Adjustable Stroke\' , \'M\' , \'Manual Valve\' , \'BR\' , \'Rear Block\' , \'BRT\' , \'Rear Trunnion\'"
part.AddCustomInfo3 "", "ACTING", 30, "Single Acting"
part.AddCustomInfo3 "", "DER", 30, "Standard"
part.AddCustomInfo3 "", "Q", 30, "Without Side Ported Rear Head"
part.AddCustomInfo3 "", "T1", 30, "without T1"
part.AddCustomInfo3 "", "T2", 30, "without T2"
part.AddCustomInfo3 "", "T3", 30, "without T3"
part.AddCustomInfo3 "", "T4", 30, "without T4"
part.AddCustomInfo3 "", "TRIM", 30, "0"
part.AddCustomInfo3 "", "Y", 30, "without Pivot Bushing"
part.AddCustomInfo3 "", "K", 30, "without K"
part.AddCustomInfo3 "", "MB", 30, "0"
part.AddCustomInfo3 "", "A1N", 30, "0.6880"
part.AddCustomInfo3 "", "A1P", 30, "1.7500"
part.AddCustomInfo3 "", "A1B", 30, "1.3750"
part.AddCustomInfo3 "", "A1S", 30, "1.5000"
part.AddCustomInfo3 "", "A2N", 30, "0.2500"
part.AddCustomInfo3 "", "A3", 30, "0.0400"
part.AddCustomInfo3 "", "D1N", 30, "1.5565"
part.AddCustomInfo3 "", "D1P", 30, "1.5565"
part.AddCustomInfo3 "", "D1B", 30, "1.5800"
part.AddCustomInfo3 "", "D2", 30, "1.5115"
part.AddCustomInfo3 "", "C1", 30, "0.0300"
part.AddCustomInfo3 "", "C2", 30, "0.0300"
part.AddCustomInfo3 "", "TAB", 30, "NPT"
part.AddCustomInfo3 "", "NDMDP", 30, "0.2730"
part.AddCustomInfo3 "", "D3", 30, "0.3440"
part.AddCustomInfo3 "", "A4", 30, "0.2500"
part.AddCustomInfo3 "", "A5", 30, "0.8700"
part.AddCustomInfo3 "", "D4", 30, "0.9730"
part.AddCustomInfo3 "", "A6", 30, "0.2500"
part.AddCustomInfo3 "", "A7", 30, "0.6250"
part.AddCustomInfo3 "", "A8", 30, "0.0000"
part.AddCustomInfo3 "", "D5", 30, "0.0000"
part.AddCustomInfo3 "", "D6", 30, "0.5320"
part.AddCustomInfo3 "", "A9", 30, "0.7320"
part.AddCustomInfo3 "", "NDM2", 30, "0.0000"
part.AddCustomInfo3 "", "TAB2", 30, "-"
part.AddCustomInfo3 "", "C11", 30, "0.0300"
part.AddCustomInfo3 "", "C22", 30, "0.0000"
part.AddCustomInfo3 "", "C33", 30, "0.0000"
part.AddCustomInfo3 "", "C44", 30, "0.0300"
part.AddCustomInfo3 "", "A10", 30, "0.6170"
part.AddCustomInfo3 "", "A11", 30, "0.0000"
part.AddCustomInfo3 "", "NDM3N", 30, "0.4050"
part.AddCustomInfo3 "", "NDM3B", 30, "0.5400"
part.AddCustomInfo3 "", "TAB3N", 30, "NPT"
part.AddCustomInfo3 "", "TAB3B", 30, "NPT"
part.AddCustomInfo3 "", "A12N", 30, "0.5620"
part.AddCustomInfo3 "", "A12B", 30, "0.7500"
part.AddCustomInfo3 "", "A13", 30, "1.3750"
part.AddCustomInfo3 "", "D7", 30, "0.3775"
part.AddCustomInfo3 "", "D8", 30, "1.0000"
part.AddCustomInfo3 "", "A14", 30, "0.0000"
part.AddCustomInfo3 "", "A15", 30, "0.0000"
part.AddCustomInfo3 "", "D9", 30, "0.0000"
part.AddCustomInfo3 "", "R1", 30, "0.0000"
part.AddCustomInfo3 "", "X1", 30, "0.9690"
part.AddCustomInfo3 "", "X2", 30, "0.2500"
part.AddCustomInfo3 "", "CX", 30, "0.0600"
part.AddCustomInfo3 "", "CC", 30, "0.0000"
part.AddCustomInfo3 "", "S1", 30, "1.7500"
part.AddCustomInfo3 "", "DB", 30, "0.4380"
part.AddCustomInfo3 "", "X1B", 30, "0.9730"
part.AddCustomInfo3 "", "X2B", 30, "0.2500"
part.AddCustomInfo3 "", "A8B", 30, "0.1250"
part.AddCustomInfo3 "", "A9B", 30, "1.0620"
part.AddCustomInfo3 "", "NDM4", 30, "0.2500"
part.AddCustomInfo3 "", "TAB4", 30, "UNC"
part.AddCustomInfo3 "", "NDM4DP", 30, "0.5000"
part.AddCustomInfo3 "", "BC", 30, "1.7500"
part.AddCustomInfo3 "", "B1", 30, "0.8750"
part.AddCustomInfo3 "", "B2", 30, "0.3800"
part.AddCustomInfo3 "", "B3", 30, "0.5000"
part.AddCustomInfo3 "", "G1", 30, "0.0000"
part.AddCustomInfo3 "", "G2", 30, "0.0000"
part.AddCustomInfo3 "", "G3", 30, "0.0000"
part.AddCustomInfo3 "", "G4", 30, "0.0000"
part.AddCustomInfo3 "", "GD", 30, "0.0000"
part.AddCustomInfo3 "", "G5", 30, "0.0000"
part.AddCustomInfo3 "", "G6", 30, "0.0000"
part.AddCustomInfo3 "", "H2", 30, "1.5800"
part.AddCustomInfo3 "", "H3", 30, "0.1250"
part.AddCustomInfo3 "", "F", 30, "0.6240"
part.AddCustomInfo3 "", "CUSH", 30, "0"
part.AddCustomInfo3 "", "CC111", 30, "0.3965"
part.AddCustomInfo3 "", "CC22", 30, "0.5625"
part.AddCustomInfo3 "", "CC33", 30, "0.3050"
part.AddCustomInfo3 "", "CC44", 30, "0.6250"
part.AddCustomInfo3 "", "CC55", 30, "0.8750"
part.AddCustomInfo3 "", "CD1", 30, "0.2650"
part.AddCustomInfo3 "", "CD2", 30, "0.1980"
part.AddCustomInfo3 "", "CD3", 30, "0.1345"
part.AddCustomInfo3 "", "CNDM3", 30, "0.2500"
part.AddCustomInfo3 "", "CTAB3", 30, "UNS"
part.AddCustomInfo3 "", "OD", 30, "0.5025"
part.AddCustomInfo3 "", "STDIS1", 30, "0.3184"
part.AddCustomInfo3 "", "BUSHCON", 30, "D-624"
part.AddCustomInfo3 "", "BUSHL", 30, "0.7500"
part.AddCustomInfo3 "", "FBON", 30, "0"
part.AddCustomInfo3 "", "LCD", 30, "0.0000"
part.AddCustomInfo3 "", "SUPPLIER", 30, "BIMBA"
part.AddCustomInfo3 "", "ARTICLENO", 30, "17P0000_rear_head"
part.AddCustomInfo3 "", "BOMINFO", 30, "17P0000_rear_head"
part.AddCustomInfo3 "", "CREATOR", 30, "CADENAS GmbH"
part.AddCustomInfo3 "", "IsFastener", 30, "0"
part.SummaryInfo(0)="17P0000_rear_head"
part.SummaryInfo(4)="Original Line - Standard Air Cylinders"
part.SummaryInfo(2)="Cadenas PARTsolutions"
valRGB=part.MaterialPropertyValues
valRGB(0)=0.82745099067688
valRGB(1)=0.82745099067688
valRGB(2)=0.82745099067688
part.MaterialPropertyValues=valRGB
Dim featMgr as object
if (sw2003api=1) then
  set featMgr=part.FeatureManager
End If
part.CreatePlaneFixed createVec3d(0,0,0),createVec3d(1,0,0),createVec3d(0,1,0),1
part.BlankRefGeom
set feat5=getLastFeatureByType(part,"RefPlane")
feat5.select false
codeBag7 part
set feat5=getLastFeatureByType(part,"ProfileFeature")
feat5.select false
if (sw2003api=0) then
  part.FeatureRevolve2 6.2831853071796,1,6.2831853071796,0,0
else
  featMgr.FeatureRevolve 6.2831853071796,1,6.2831853071796,0,0,1,1,1
end if
part.CreatePlaneFixed createVec3d(0,0,0),createVec3d(1,0,0),createVec3d(0,1,0),1
part.BlankRefGeom
set feat7=getLastFeatureByType(part,"RefPlane")
feat7.select false
codeBag8 part
set feat7=getLastFeatureByType(part,"ProfileFeature")
feat7.select false
if (sw2003api=0) then
  part.FeatureRevolve2 6.2831853071796,1,6.2831853071796,0,0
else
  featMgr.FeatureRevolve 6.2831853071796,1,6.2831853071796,0,0,1,1,1
end if
part.CreatePlaneFixed createVec3d(0.04445,0,0),createVec3d(0.04445,0,-1),createVec3d(0.04445,1,0),1
part.BlankRefGeom
set feat9=getLastFeatureByType(part,"RefPlane")
feat9.select false
codeBag9 part
set feat9=getLastFeatureByType(part,"ProfileFeature")
feat9.select false
if (sw2003api=0) then
  part.FeatureCut 1,0,0,0,0,0.022225,0.022225,1,1,0,0,0,0,0,0
else
  featMgr.FeatureCut 1,0,0,0,0,0.022225,0.022225,1,1,0,0,0,0,0,0,0,0,0,1,1
end if
part.CreatePlaneFixed createVec3d(0,0,0),createVec3d(1,0,0),createVec3d(0,1,0),1
part.BlankRefGeom
set feat12=getLastFeatureByType(part,"RefPlane")
feat12.select false
codeBag10 part
set feat12=getLastFeatureByType(part,"ProfileFeature")
feat12.select false
if (sw2003api=0) then
  part.FeatureRevolveCut2 6.2831853071796,1,6.2831853071796,0,0
else
  featMgr.FeatureRevolveCut 6.2831853071796,1,6.2831853071796,0,0,1,1
end if
part.CreatePlaneFixed createVec3d(0,0,0),createVec3d(1,0,0),createVec3d(0,0.017452406437284,-0.99984769515639),1
part.BlankRefGeom
set feat15=getLastFeatureByType(part,"RefPlane")
feat15.select false
codeBag11 part
set feat15=getLastFeatureByType(part,"ProfileFeature")
feat15.select false
if (sw2003api=0) then
  part.FeatureRevolveCut2 6.2831853071796,1,6.2831853071796,0,0
else
  featMgr.FeatureRevolveCut 6.2831853071796,1,6.2831853071796,0,0,1,1
end if
part.CreatePlaneFixed createVec3d(0,0,0),createVec3d(1,0,0),createVec3d(0,1,0),1
part.BlankRefGeom
set feat18=getLastFeatureByType(part,"RefPlane")
feat18.select false
codeBag12 part
set feat18=getLastFeatureByType(part,"ProfileFeature")
feat18.select false
if (sw2003api=0) then
  part.FeatureRevolveCut2 6.2831853071796,1,6.2831853071796,0,0
else
  featMgr.FeatureRevolveCut 6.2831853071796,1,6.2831853071796,0,0,1,1
end if
part.CreatePlaneFixed createVec3d(0,0,0),createVec3d(1,0,0),createVec3d(0,1,0),1
part.BlankRefGeom
set feat21=getLastFeatureByType(part,"RefPlane")
feat21.select false
codeBag13 part
set feat21=getLastFeatureByType(part,"ProfileFeature")
feat21.select false
if (sw2003api=0) then
  part.FeatureRevolve2 6.2831853071796,1,6.2831853071796,0,0
else
  featMgr.FeatureRevolve 6.2831853071796,1,6.2831853071796,0,0,1,1,1
end if
part.CreatePlaneFixed createVec3d(0,0,0),createVec3d(1,0,0),createVec3d(0,1,0),1
part.BlankRefGeom
set feat24=getLastFeatureByType(part,"RefPlane")
feat24.select false
codeBag14 part
set feat24=getLastFeatureByType(part,"ProfileFeature")
feat24.select false
if (sw2003api=0) then
  part.FeatureCut 0,0,0,0,0,0.01175385,0.01175385,1,1,0,0,0,0,0,0
else
  featMgr.FeatureCut 0,0,0,0,0,0.01175385,0.01175385,1,1,0,0,0,0,0,0,0,0,0,1,1
end if
part.SetDisplayWhenAdded (true)
part.SetAddToDB(false)
part.EditRebuild3
part.Rebuild swRebuildAll
part.SaveAs2 storePath & "17P0000_rear_head.sldprt",0,0,false
End Sub
Sub CreatePart4
dim error as long
set res=swApp.OpenDoc2 ( storePath & "D-358.sldprt",1,true,false,true,error)
if not res is nothing then
 exit sub
end if
set part=swApp.NewPart
part.SetAddToDB(true)
part.SetDisplayWhenAdded (false)
part.SetUnits 3,2,64,5,false
part.AddCustomInfo3 "", "NN", 30, "Pin"
part.AddCustomInfo3 "", "NT", 30, "Original Line - Standard Air Cylinders"
part.AddCustomInfo3 "", "NB", 30, "D-358"
part.AddCustomInfo3 "", "NBSYN", 30, "$PN."
part.AddCustomInfo3 "", "LINA", 30, "D-358"
part.AddCustomInfo3 "", "PN", 30, "D-358"
part.AddCustomInfo3 "", "DIA", 30, "0.37500"
part.AddCustomInfo3 "", "L", 30, "1.0000"
part.AddCustomInfo3 "", "SUPPLIER", 30, "BIMBA"
part.AddCustomInfo3 "", "ARTICLENO", 30, "D-358"
part.AddCustomInfo3 "", "BOMINFO", 30, "D-358"
part.AddCustomInfo3 "", "CREATOR", 30, "CADENAS GmbH"
part.AddCustomInfo3 "", "IsFastener", 30, "0"
part.SummaryInfo(0)="D-358"
part.SummaryInfo(4)="Original Line - Standard Air Cylinders"
part.SummaryInfo(2)="Cadenas PARTsolutions"
valRGB=part.MaterialPropertyValues
valRGB(0)=0.75294119119644
valRGB(1)=0.75294119119644
valRGB(2)=0.75294119119644
part.MaterialPropertyValues=valRGB
Dim featMgr as object
if (sw2003api=1) then
  set featMgr=part.FeatureManager
End If
part.CreatePlaneFixed createVec3d(0,0,0),createVec3d(0,0,-1),createVec3d(0,1,0),1
part.BlankRefGeom
set feat4=getLastFeatureByType(part,"RefPlane")
feat4.select false
codeBag15 part
set feat4=getLastFeatureByType(part,"ProfileFeature")
feat4.select false
if (sw2003api=0) then
  part.FeatureRevolve2 6.2831853071796,1,6.2831853071796,0,0
else
  featMgr.FeatureRevolve 6.2831853071796,1,6.2831853071796,0,0,1,1,1
end if
part.SetDisplayWhenAdded (true)
part.SetAddToDB(false)
part.EditRebuild3
part.Rebuild swRebuildAll
part.SaveAs2 storePath & "D-358.sldprt",0,0,false
End Sub
Sub CreatePart5
dim error as long
set res=swApp.OpenDoc2 ( storePath & "C-170_5-P0_rod.sldprt",1,true,false,true,error)
if not res is nothing then
 exit sub
end if
set part=swApp.NewPart
part.SetAddToDB(true)
part.SetDisplayWhenAdded (false)
part.SetUnits 3,2,64,5,false
part.AddCustomInfo3 "", "NN", 30, "Standard Air Cylinder_rod"
part.AddCustomInfo3 "", "NT", 30, "Original Line - Standard Air Cylinders"
part.AddCustomInfo3 "", "NB", 30, "C-170.5-P0_rod"
part.AddCustomInfo3 "", "NBSYN", 30, "$PN.$COLOR1._rod"
part.AddCustomInfo3 "", "LINA", 30, "C-170.5-P0_rod"
part.AddCustomInfo3 "", "PN", 30, "C-170.5-P"
part.AddCustomInfo3 "", "BORE", 30, "1.50000000"
part.AddCustomInfo3 "", "BOREPN", 30, "17"
part.AddCustomInfo3 "", "STROKE", 30, "0.500"
part.AddCustomInfo3 "", "ACTING", 30, "Single Acting"
part.AddCustomInfo3 "", "MNT", 30, "Rear Pivot Mounting"
part.AddCustomInfo3 "", "DER", 30, "N/A"
part.AddCustomInfo3 "", "NR", 30, "Standard"
part.AddCustomInfo3 "", "BM", 30, "N/A"
part.AddCustomInfo3 "", "CO", 30, "N/A"
part.AddCustomInfo3 "", "M", 30, "Without Magnet"
part.AddCustomInfo3 "", "EE", 30, "Without Extra Extension"
part.AddCustomInfo3 "", "EEL", 30, "0"
part.AddCustomInfo3 "", "K", 30, "Standard"
part.AddCustomInfo3 "", "Q", 30, "Without Side Ported Rear Head"
part.AddCustomInfo3 "", "Y", 30, "Without Pivot Bushing"
part.AddCustomInfo3 "", "F", 30, "Standard"
part.AddCustomInfo3 "", "G", 30, "Without Magnalube Lubrication"
part.AddCustomInfo3 "", "T", 30, "Standard"
part.AddCustomInfo3 "", "B", 30, "Without Bumper"
part.AddCustomInfo3 "", "H", 30, "Standard"
part.AddCustomInfo3 "", "SER", 30, "N/A"
part.AddCustomInfo3 "", "SR", 30, "Carbon Steel Rod"
part.AddCustomInfo3 "", "NT", 30, "Standard"
part.AddCustomInfo3 "", "W", 30, "N/A"
part.AddCustomInfo3 "", "E", 30, "Without Special Lube and Seals"
part.AddCustomInfo3 "", "HL", 30, "N/A"
part.AddCustomInfo3 "", "ST", 30, "Without Switch Track"
part.AddCustomInfo3 "", "STP", 30, "N/A"
part.AddCustomInfo3 "", "PRC", 30, "Without Piston Rod Clevis"
part.AddCustomInfo3 "", "PB", 30, "Without Pivot Bracket"
part.AddCustomInfo3 "", "A1N", 30, "1.3120"
part.AddCustomInfo3 "", "A1P", 30, "1.8750"
part.AddCustomInfo3 "", "A1B", 30, "2.3750"
part.AddCustomInfo3 "", "A4N", 30, "0.5000"
part.AddCustomInfo3 "", "A4P", 30, "0.2525"
part.AddCustomInfo3 "", "A5", 30, "0.0400"
part.AddCustomInfo3 "", "A1NH", 30, "0.6880"
part.AddCustomInfo3 "", "A1PH", 30, "1.7500"
part.AddCustomInfo3 "", "A1BH", 30, "1.3750"
part.AddCustomInfo3 "", "A1SH", 30, "1.5000"
part.AddCustomInfo3 "", "A2NH", 30, "0.2500"
part.AddCustomInfo3 "", "A13", 30, "1.3750"
part.AddCustomInfo3 "", "THDLEN1", 30, "0.7500"
part.AddCustomInfo3 "", "THD1", 30, "0.4375"
part.AddCustomInfo3 "", "TAB", 30, "UNF"
part.AddCustomInfo3 "", "OD", 30, "1.5115"
part.AddCustomInfo3 "", "RODDIA", 30, "0.4370"
part.AddCustomInfo3 "", "HEX", 30, "0.4370"
part.AddCustomInfo3 "", "G1", 30, "0.0000"
part.AddCustomInfo3 "", "G5", 30, "0.0000"
part.AddCustomInfo3 "", "THOLE", 30, "0.2500"
part.AddCustomInfo3 "", "WF", 30, "0.3800"
part.AddCustomInfo3 "", "GROOVE", 30, "1"
part.AddCustomInfo3 "", "D7", 30, "0.3775"
part.AddCustomInfo3 "", "D1P", 30, "1.5800"
part.AddCustomInfo3 "", "D1B", 30, "1.5565"
part.AddCustomInfo3 "", "D1N", 30, "1.5565"
part.AddCustomInfo3 "", "D1NRH", 30, "1.5565"
part.AddCustomInfo3 "", "D1BRH", 30, "1.5800"
part.AddCustomInfo3 "", "D1PRH", 30, "1.5565"
part.AddCustomInfo3 "", "COLOR1", 30, "0"
part.AddCustomInfo3 "", "SUPPLIER", 30, "BIMBA"
part.AddCustomInfo3 "", "ARTICLENO", 30, "C-170.5-P0_rod"
part.AddCustomInfo3 "", "BOMINFO", 30, "C-170.5-P0_rod"
part.AddCustomInfo3 "", "CREATOR", 30, "CADENAS GmbH"
part.AddCustomInfo3 "", "IsFastener", 30, "0"
part.SummaryInfo(0)="C-170.5-P0_rod"
part.SummaryInfo(4)="Original Line - Standard Air Cylinders"
part.SummaryInfo(2)="Cadenas PARTsolutions"
valRGB=part.MaterialPropertyValues
valRGB(0)=0
valRGB(1)=0
valRGB(2)=0
part.MaterialPropertyValues=valRGB
Dim featMgr as object
if (sw2003api=1) then
  set featMgr=part.FeatureManager
End If
part.CreatePlaneFixed createVec3d(0,0,0),createVec3d(1,0,0),createVec3d(0,1,0),1
part.BlankRefGeom
set feat4=getLastFeatureByType(part,"RefPlane")
feat4.select false
codeBag16 part
set feat4=getLastFeatureByType(part,"ProfileFeature")
feat4.select false
if (sw2003api=0) then
  part.FeatureRevolve2 6.2831853071796,1,6.2831853071796,0,0
else
  featMgr.FeatureRevolve 6.2831853071796,1,6.2831853071796,0,0,1,1,1
end if
part.CreatePlaneFixed createVec3d(0,0,0),createVec3d(1,0,0),createVec3d(0,1,0),1
part.BlankRefGeom
set feat6=getLastFeatureByType(part,"RefPlane")
feat6.select false
codeBag17 part
set feat6=getLastFeatureByType(part,"ProfileFeature")
feat6.select false
if (sw2003api=0) then
  part.FeatureRevolve2 6.2831853071796,1,6.2831853071796,0,0
else
  featMgr.FeatureRevolve 6.2831853071796,1,6.2831853071796,0,0,1,1,1
end if
if sw2003api=1 then
  if getEdgeFromModel(part,createVec3d(-0.02464435,-0.00555625,0),cylEdge) then
    cylEdge.Select(false)
    Part.InsertCosmeticThread 0,0.0096012,0.01905,""
  elseif getEdgeFromModel(part,createVec3d(-0.00635,-0.00555625,0),cylEdge) then
    cylEdge.Select(false)
    Part.InsertCosmeticThread 0,0.0096012,0.01905,""
  End If
End If
part.CreatePlaneFixed createVec3d(-0.00635,0,0),createVec3d(-0.00635,0,-1),createVec3d(-0.00635,1,0),1
part.BlankRefGeom
set feat10=getLastFeatureByType(part,"RefPlane")
feat10.select false
codeBag18 part
set feat10=getLastFeatureByType(part,"ProfileFeature")
feat10.select false
if (sw2003api=0) then
  part.FeatureCut 1,0,1,0,0,0.00635,0.00635,1,1,0,0,0,0,0,0
else
  featMgr.FeatureCut 1,0,1,0,0,0.00635,0.00635,1,1,0,0,0,0,0,0,0,0,0,1,1
end if
part.SetDisplayWhenAdded (true)
part.SetAddToDB(false)
part.EditRebuild3
part.Rebuild swRebuildAll
part.SaveAs2 storePath & "C-170_5-P0_rod.sldprt",0,0,false
End Sub
Sub CreatePart6
dim error as long
set res=swApp.OpenDoc2 ( storePath & "D-231-1-dummy.sldprt",1,true,false,true,error)
if not res is nothing then
 exit sub
end if
set part=swApp.NewPart
part.SetAddToDB(true)
part.SetDisplayWhenAdded (false)
part.SetUnits 3,2,64,5,false
part.AddCustomInfo3 "", "NN", 30, "Piston Rod Clevis for Original Line Cylinders - dummy"
part.AddCustomInfo3 "", "NB", 30, "D-231-1-dummy"
part.AddCustomInfo3 "", "NBSYN", 30, "$PN.-dummy"
part.AddCustomInfo3 "", "LINA", 30, "D-231-1-dummy"
part.AddCustomInfo3 "", "PN", 30, "D-231-1"
part.AddCustomInfo3 "", "MAT", 30, "Zinc-Plated Carbon Steel"
part.AddCustomInfo3 "", "DWGRR", 30, "D-5867"
part.AddCustomInfo3 "", "DWGCP", 30, "D-8383"
part.AddCustomInfo3 "", "DWGREC", 30, "D-14053"
part.AddCustomInfo3 "", "DWGN", 30, "D-154"
part.AddCustomInfo3 "", "TH", 30, "0.10000000"
part.AddCustomInfo3 "", "TO", 30, "1.50000000"
part.AddCustomInfo3 "", "TO1", 30, "0.25000000"
part.AddCustomInfo3 "", "L1", 30, "1.31200000"
part.AddCustomInfo3 "", "B", 30, "0.2500"
part.AddCustomInfo3 "", "L2", 30, "0.7500"
part.AddCustomInfo3 "", "L", 30, "1.68800"
part.AddCustomInfo3 "", "SUPPLIER", 30, "BIMBA"
part.AddCustomInfo3 "", "ARTICLENO", 30, "D-231-1-dummy"
part.AddCustomInfo3 "", "BOMINFO", 30, "D-231-1-dummy"
part.AddCustomInfo3 "", "CREATOR", 30, "CADENAS GmbH"
part.AddCustomInfo3 "", "IsFastener", 30, "1"
part.SummaryInfo(0)="D-231-1-dummy"
part.SummaryInfo(2)="Cadenas PARTsolutions"
valRGB=part.MaterialPropertyValues
valRGB(0)=0.81568628549576
valRGB(1)=0.42352941632271
valRGB(2)=0.31764706969261
part.MaterialPropertyValues=valRGB
Dim featMgr as object
if (sw2003api=1) then
  set featMgr=part.FeatureManager
End If
part.SetDisplayWhenAdded (true)
part.SetAddToDB(false)
part.EditRebuild3
part.Rebuild swRebuildAll
part.SaveAs2 storePath & "D-231-1-dummy.sldprt",0,0,false
End Sub
Sub CreatePart7
dim error as long
set res=swApp.OpenDoc2 ( storePath & "D-14053.sldprt",1,true,false,true,error)
if not res is nothing then
 exit sub
end if
set part=swApp.NewPart
part.SetAddToDB(true)
part.SetDisplayWhenAdded (false)
part.SetUnits 3,2,64,5,false
part.AddCustomInfo3 "", "NN", 30, "Piston Rod Clevis for Original Line Cylinders - Body"
part.AddCustomInfo3 "", "NB", 30, "D-14053"
part.AddCustomInfo3 "", "NBSYN", 30, "$PN."
part.AddCustomInfo3 "", "LINA", 30, "D-14053"
part.AddCustomInfo3 "", "PN", 30, "D-14053"
part.AddCustomInfo3 "", "L", 30, "1.68800000"
part.AddCustomInfo3 "", "L1", 30, "1.31200000"
part.AddCustomInfo3 "", "L2", 30, "0.75000000"
part.AddCustomInfo3 "", "W", 30, "0.38750000"
part.AddCustomInfo3 "", "W1", 30, "0.75000000"
part.AddCustomInfo3 "", "DIA1", 30, "0.37200000"
part.AddCustomInfo3 "", "DIA1CS", 30, "0.04500000"
part.AddCustomInfo3 "", "DIA2", 30, "0.75000000"
part.AddCustomInfo3 "", "DIA3", 30, "0.39060000"
part.AddCustomInfo3 "", "CS", 30, "90.00000000"
part.AddCustomInfo3 "", "CDP", 30, "0.03000000"
part.AddCustomInfo3 "", "AN", 30, "30.00000000"
part.AddCustomInfo3 "", "NDM", 30, "0.43750000"
part.AddCustomInfo3 "", "CODE", 30, "UNF"
part.AddCustomInfo3 "", "NDMDP", 30, "0.62000000"
part.AddCustomInfo3 "", "SUPPLIER", 30, "BIMBA"
part.AddCustomInfo3 "", "ARTICLENO", 30, "D-14053"
part.AddCustomInfo3 "", "BOMINFO", 30, "D-14053"
part.AddCustomInfo3 "", "CREATOR", 30, "CADENAS GmbH"
part.AddCustomInfo3 "", "IsFastener", 30, "0"
part.SummaryInfo(0)="D-14053"
part.SummaryInfo(2)="Cadenas PARTsolutions"
valRGB=part.MaterialPropertyValues
valRGB(0)=0.75
valRGB(1)=0.75
valRGB(2)=0.75
part.MaterialPropertyValues=valRGB
Dim featMgr as object
if (sw2003api=1) then
  set featMgr=part.FeatureManager
End If
part.CreatePlaneFixed createVec3d(0,0,0),createVec3d(1,0,0),createVec3d(0,1,0),1
part.BlankRefGeom
set feat4=getLastFeatureByType(part,"RefPlane")
feat4.select false
codeBag19 part
set feat4=getLastFeatureByType(part,"ProfileFeature")
feat4.select false
if (sw2003api=0) then
  part.FeatureExtrusion 0,0,1,0,0,0.009525,0.009525,1,1,0,0,0,0,0,0
else
  featMgr.FeatureExtrusion 0,0,1,0,0,0.009525,0.009525,1,1,0,0,0,0,0,0,0,0,1,1,1
end if
part.CreatePlaneFixed createVec3d(0,0,0),createVec3d(1,0,0),createVec3d(0,0,-1),1
part.BlankRefGeom
set feat6=getLastFeatureByType(part,"RefPlane")
feat6.select false
codeBag20 part
set feat6=getLastFeatureByType(part,"ProfileFeature")
feat6.select false
if (sw2003api=0) then
  part.FeatureCut 0,0,0,0,0,0.009525,0.009525,1,1,0,0,0,0,0,0
else
  featMgr.FeatureCut 0,0,0,0,0,0.009525,0.009525,1,1,0,0,0,0,0,0,0,0,0,1,1
end if
part.CreatePlaneFixed createVec3d(0,0,0),createVec3d(1,0,0),createVec3d(0,1,0),1
part.BlankRefGeom
set feat8=getLastFeatureByType(part,"RefPlane")
feat8.select false
codeBag21 part
set feat8=getLastFeatureByType(part,"ProfileFeature")
feat8.select false
if (sw2003api=0) then
  part.FeatureRevolveCut2 6.2831853071796,1,6.2831853071796,0,0
else
  featMgr.FeatureRevolveCut 6.2831853071796,1,6.2831853071796,0,0,1,1
end if
part.CreatePlaneFixed createVec3d(0,0,0),createVec3d(1,0,0),createVec3d(0,1,0),1
part.BlankRefGeom
set feat13=getLastFeatureByType(part,"RefPlane")
feat13.select false
codeBag22 part
set feat13=getLastFeatureByType(part,"ProfileFeature")
feat13.select false
if (sw2003api=0) then
  part.FeatureRevolveCut2 6.2831853071796,1,6.2831853071796,0,0
else
  featMgr.FeatureRevolveCut 6.2831853071796,1,6.2831853071796,0,0,1,1
end if
part.CreatePlaneFixed createVec3d(0,0,0),createVec3d(0,0,-1),createVec3d(0,1,0),1
part.BlankRefGeom
set feat15=getLastFeatureByType(part,"RefPlane")
feat15.select false
codeBag23 part
set feat15=getLastFeatureByType(part,"ProfileFeature")
feat15.select false
if (sw2003api=0) then
  part.FeatureRevolveCut2 6.2831853071796,1,6.2831853071796,0,0
else
  featMgr.FeatureRevolveCut 6.2831853071796,1,6.2831853071796,0,0,1,1
end if
part.CreatePlaneFixed createVec3d(0,0,0),createVec3d(1,0,0),createVec3d(0,1,0),1
part.BlankRefGeom
set feat17=getLastFeatureByType(part,"RefPlane")
feat17.select false
codeBag24 part
set feat17=getLastFeatureByType(part,"ProfileFeature")
feat17.select false
if (sw2003api=0) then
  part.FeatureRevolveCut2 6.2831853071796,1,6.2831853071796,0,0
else
  featMgr.FeatureRevolveCut 6.2831853071796,1,6.2831853071796,0,0,1,1
end if
part.CreatePlaneFixed createVec3d(0,0,0),createVec3d(1,0,0),createVec3d(0,1,0),1
part.BlankRefGeom
set feat19=getLastFeatureByType(part,"RefPlane")
feat19.select false
codeBag25 part
set feat19=getLastFeatureByType(part,"ProfileFeature")
feat19.select false
if (sw2003api=0) then
  part.FeatureRevolveCut2 6.2831853071796,1,6.2831853071796,0,0
else
  featMgr.FeatureRevolveCut 6.2831853071796,1,6.2831853071796,0,0,1,1
end if
part.SetDisplayWhenAdded (true)
part.SetAddToDB(false)
part.EditRebuild3
part.Rebuild swRebuildAll
part.SaveAs2 storePath & "D-14053.sldprt",0,0,false
End Sub
Sub CreatePart8
dim error as long
set res=swApp.OpenDoc2 ( storePath & "D-8383.sldprt",1,true,false,true,error)
if not res is nothing then
 exit sub
end if
set part=swApp.NewPart
part.SetAddToDB(true)
part.SetDisplayWhenAdded (false)
part.SetUnits 3,2,64,5,false
part.AddCustomInfo3 "", "NN", 30, "Piston Rod Clevis for Original Line Cylinders - Pin"
part.AddCustomInfo3 "", "NB", 30, "D-8383"
part.AddCustomInfo3 "", "NBSYN", 30, "$PN."
part.AddCustomInfo3 "", "LINA", 30, "D-8383"
part.AddCustomInfo3 "", "PN", 30, "D-8383"
part.AddCustomInfo3 "", "L", 30, "1.03100000"
part.AddCustomInfo3 "", "L1", 30, "0.75500000"
part.AddCustomInfo3 "", "L2", 30, "0.04050000"
part.AddCustomInfo3 "", "L4", 30, "0.09800000"
part.AddCustomInfo3 "", "D", 30, "0.37650000"
part.AddCustomInfo3 "", "D1", 30, "0.30450000"
part.AddCustomInfo3 "", "CH", 30, "0.01500000"
part.AddCustomInfo3 "", "R", 30, "0.00250000"
part.AddCustomInfo3 "", "SUPPLIER", 30, "BIMBA"
part.AddCustomInfo3 "", "ARTICLENO", 30, "D-8383"
part.AddCustomInfo3 "", "BOMINFO", 30, "D-8383"
part.AddCustomInfo3 "", "CREATOR", 30, "CADENAS GmbH"
part.AddCustomInfo3 "", "IsFastener", 30, "0"
part.SummaryInfo(0)="D-8383"
part.SummaryInfo(2)="Cadenas PARTsolutions"
valRGB=part.MaterialPropertyValues
valRGB(0)=0.75
valRGB(1)=0.75
valRGB(2)=0.75
part.MaterialPropertyValues=valRGB
Dim featMgr as object
if (sw2003api=1) then
  set featMgr=part.FeatureManager
End If
part.CreatePlaneFixed createVec3d(0,0,0),createVec3d(1,0,0),createVec3d(0,1,0),1
part.BlankRefGeom
set feat4=getLastFeatureByType(part,"RefPlane")
feat4.select false
codeBag26 part
set feat4=getLastFeatureByType(part,"ProfileFeature")
feat4.select false
if (sw2003api=0) then
  part.FeatureRevolve2 6.2831853071796,1,6.2831853071796,0,0
else
  featMgr.FeatureRevolve 6.2831853071796,1,6.2831853071796,0,0,1,1,1
end if
part.SetDisplayWhenAdded (true)
part.SetAddToDB(false)
part.EditRebuild3
part.Rebuild swRebuildAll
part.SaveAs2 storePath & "D-8383.sldprt",0,0,false
End Sub
Sub CreatePart9
dim error as long
set res=swApp.OpenDoc2 ( storePath & "D-5867.sldprt",1,true,false,true,error)
if not res is nothing then
 exit sub
end if
set part=swApp.NewPart
part.SetAddToDB(true)
part.SetDisplayWhenAdded (false)
part.SetUnits 3,2,64,5,false
part.AddCustomInfo3 "", "NN", 30, "Piston Rod Clevis for Original Line Cylinders - Retaining Ring"
part.AddCustomInfo3 "", "NB", 30, "D-5867"
part.AddCustomInfo3 "", "NBSYN", 30, "$PN."
part.AddCustomInfo3 "", "LINA", 30, "D-5867"
part.AddCustomInfo3 "", "PN", 30, "D-5867"
part.AddCustomInfo3 "", "D", 30, "0.75000000"
part.AddCustomInfo3 "", "D1", 30, "0.30500000"
part.AddCustomInfo3 "", "L", 30, "0.03650000"
part.AddCustomInfo3 "", "SUPPLIER", 30, "BIMBA"
part.AddCustomInfo3 "", "ARTICLENO", 30, "D-5867"
part.AddCustomInfo3 "", "BOMINFO", 30, "D-5867"
part.AddCustomInfo3 "", "CREATOR", 30, "CADENAS GmbH"
part.AddCustomInfo3 "", "IsFastener", 30, "0"
part.SummaryInfo(0)="D-5867"
part.SummaryInfo(2)="Cadenas PARTsolutions"
valRGB=part.MaterialPropertyValues
valRGB(0)=0.32941177487373
valRGB(1)=0.32941177487373
valRGB(2)=0.32941177487373
part.MaterialPropertyValues=valRGB
Dim featMgr as object
if (sw2003api=1) then
  set featMgr=part.FeatureManager
End If
part.CreatePlaneFixed createVec3d(0,0,0),createVec3d(1,0,0),createVec3d(0,1,0),1
part.BlankRefGeom
set feat4=getLastFeatureByType(part,"RefPlane")
feat4.select false
codeBag27 part
set feat4=getLastFeatureByType(part,"ProfileFeature")
feat4.select false
if (sw2003api=0) then
  part.FeatureExtrusion 0,0,1,0,0,0.00046355,0.00046355,1,1,0,0,0,0,0,0
else
  featMgr.FeatureExtrusion 0,0,1,0,0,0.00046355,0.00046355,1,1,0,0,0,0,0,0,0,0,1,1,1
end if
part.SetDisplayWhenAdded (true)
part.SetAddToDB(false)
part.EditRebuild3
part.Rebuild swRebuildAll
part.SaveAs2 storePath & "D-5867.sldprt",0,0,false
End Sub
Sub CreatePart10
dim error as long
set res=swApp.OpenDoc2 ( storePath & "D-154.sldprt",1,true,false,true,error)
if not res is nothing then
 exit sub
end if
set part=swApp.NewPart
part.SetAddToDB(true)
part.SetDisplayWhenAdded (false)
part.SetUnits 3,2,64,5,false
part.AddCustomInfo3 "", "NN", 30, "Mounting Nut for Original Line Cylinders"
part.AddCustomInfo3 "", "NB", 30, "D-154"
part.AddCustomInfo3 "", "NBSYN", 30, "$PN."
part.AddCustomInfo3 "", "LINA", 30, "D-154"
part.AddCustomInfo3 "", "PN", 30, "D-154"
part.AddCustomInfo3 "", "C", 30, "7/16-20"
part.AddCustomInfo3 "", "MAT", 30, "Zinc-Plated Carbon Steel"
part.AddCustomInfo3 "", "A", 30, "0.69"
part.AddCustomInfo3 "", "B", 30, "0.25"
part.AddCustomInfo3 "", "DIA", 30, "-"
part.AddCustomInfo3 "", "T", 30, "-"
part.AddCustomInfo3 "", "SUPPLIER", 30, "BIMBA"
part.AddCustomInfo3 "", "ARTICLENO", 30, "D-154"
part.AddCustomInfo3 "", "BOMINFO", 30, "D-154"
part.AddCustomInfo3 "", "CREATOR", 30, "CADENAS GmbH"
part.AddCustomInfo3 "", "IsFastener", 30, "0"
part.SummaryInfo(0)="D-154"
part.SummaryInfo(2)="Cadenas PARTsolutions"
valRGB=part.MaterialPropertyValues
valRGB(0)=0.75
valRGB(1)=0.75
valRGB(2)=0.75
part.MaterialPropertyValues=valRGB
Dim featMgr as object
if (sw2003api=1) then
  set featMgr=part.FeatureManager
End If
part.CreatePlaneFixed createVec3d(0,0,0),createVec3d(0,0,-1),createVec3d(0,1,0),1
part.BlankRefGeom
set feat5=getLastFeatureByType(part,"RefPlane")
feat5.select false
codeBag28 part
set feat5=getLastFeatureByType(part,"ProfileFeature")
feat5.select false
if (sw2003api=0) then
  part.FeatureRevolve2 6.2831853071796,1,6.2831853071796,0,0
else
  featMgr.FeatureRevolve 6.2831853071796,1,6.2831853071796,0,0,1,1,1
end if
part.CreatePlaneFixed createVec3d(0,0,0),createVec3d(1,0,0),createVec3d(0,1,0),1
part.BlankRefGeom
set feat6=getLastFeatureByType(part,"RefPlane")
feat6.select false
codeBag29 part
set feat6=getLastFeatureByType(part,"ProfileFeature")
feat6.select false
if (sw2003api=0) then
  part.FeatureCut 1,0,0,0,0,0.00635,0.00635,1,1,0,0,0,0,0,0
else
  featMgr.FeatureCut 1,0,0,0,0,0.00635,0.00635,1,1,0,0,0,0,0,0,0,0,0,1,1
end if
part.CreatePlaneFixed createVec3d(0,0,0),createVec3d(0,0,-1),createVec3d(0,1,0),1
part.BlankRefGeom
set feat8=getLastFeatureByType(part,"RefPlane")
feat8.select false
codeBag30 part
set feat8=getLastFeatureByType(part,"ProfileFeature")
feat8.select false
if (sw2003api=0) then
  part.FeatureRevolveCut2 6.2831853071796,1,6.2831853071796,0,0
else
  featMgr.FeatureRevolveCut 6.2831853071796,1,6.2831853071796,0,0,1,1
end if
part.SetDisplayWhenAdded (true)
part.SetAddToDB(false)
part.EditRebuild3
part.Rebuild swRebuildAll
part.SaveAs2 storePath & "D-154.sldprt",0,0,false
End Sub
sub CreatePart11
dim error as long
set res=swApp.OpenDoc2 ( storePath & "170_5-P(F,D-231-1).sldasm",2,true,false,true,error)
if not res is nothing then
 exit sub
end if
if (docVisible=0) then
 swApp.DocumentVisible 0, 1
end if
createPart0
createPart1
createPart2
createPart3
createPart4
createPart5
createPart6
createPart7
createPart8
createPart9
createPart9
createPart10
swApp.DocumentVisible 1, 1
set part=swApp.NewAssembly
part.SetUnits 3,2,64,5,false
part.AddCustomInfo3 "", "NN", 30, "Original Line Standard Air Cylinders"
part.AddCustomInfo3 "", "NB", 30, "170.5-P(F,D-231-1)"
part.AddCustomInfo3 "", "NBSYN", 30, "$PNC."
part.AddCustomInfo3 "", "LINA", 30, "170.5-P"
part.AddCustomInfo3 "", "PN", 30, "170.5-P"
part.AddCustomInfo3 "", "PNA", 30, "(D-231-1)"
part.AddCustomInfo3 "", "BORE", 30, "1 1/2" & Chr(34) & " [17]"
part.AddCustomInfo3 "", "STROKE", 30, "0.500"
part.AddCustomInfo3 "", "ACTING", 30, "Standard Single"
part.AddCustomInfo3 "", "MNT", 30, "Rear Pivot [P]"
part.AddCustomInfo3 "", "DER", 30, "N/A"
part.AddCustomInfo3 "", "NR", 30, "Standard Round"
part.AddCustomInfo3 "", "BM", 30, "N/A"
part.AddCustomInfo3 "", "CO", 30, "N/A"
part.AddCustomInfo3 "", "OO", 30, "N/A"
part.AddCustomInfo3 "", "VO", 30, "N/A"
part.AddCustomInfo3 "", "M", 30, "Without Magnet Piston"
part.AddCustomInfo3 "", "EE", 30, "Standard Rod Extension"
part.AddCustomInfo3 "", "EEL", 30, "0.000"
part.AddCustomInfo3 "", "K", 30, "Standard"
part.AddCustomInfo3 "", "Q", 30, "N/A"
part.AddCustomInfo3 "", "Y", 30, "Standard Pivot Style"
part.AddCustomInfo3 "", "G", 30, "Standard Grease Lube"
part.AddCustomInfo3 "", "T", 30, "Standard -20 to 200F (-29 to 95C)"
part.AddCustomInfo3 "", "B", 30, "Without Bumpers"
part.AddCustomInfo3 "", "H", 30, "Standard (7 - 14 lbs.)"
part.AddCustomInfo3 "", "SER", 30, "N/A"
part.AddCustomInfo3 "", "SR", 30, "Standard Blackened Carbon Steel"
part.AddCustomInfo3 "", "NT", 30, "Standard Male Thread"
part.AddCustomInfo3 "", "W", 30, "N/A"
part.AddCustomInfo3 "", "HL", 30, "N/A"
part.AddCustomInfo3 "", "STPT1", 30, "N/A"
part.AddCustomInfo3 "", "STPT2", 30, "N/A"
part.AddCustomInfo3 "", "STPT3", 30, "N/A"
part.AddCustomInfo3 "", "STPT4", 30, "N/A"
part.AddCustomInfo3 "", "MB", 30, "Without Mounting Bracket"
part.AddCustomInfo3 "", "PB", 30, "Without Pivot Bracket"
part.AddCustomInfo3 "", "PRC", 30, "D-231-1 (front)"
part.AddCustomInfo3 "", "TB", 30, "N/A"
part.AddCustomInfo3 "", "MN", 30, "Without Mounting Nut"
part.AddCustomInfo3 "", "A", 30, "4.31"
part.AddCustomInfo3 "", "SUPPLIER", 30, "BIMBA"
part.AddCustomInfo3 "", "ARTICLENO", 30, "170.5-P(F,D-231-1)"
part.AddCustomInfo3 "", "BOMINFO", 30, "170.5-P"
part.AddCustomInfo3 "", "CREATOR", 30, "CADENAS GmbH"
part.SummaryInfo(0)="170.5-P"
part.SummaryInfo(2)="Cadenas PARTsolutions"
set comp=part.AddComponent2 ( storePath &"170_5-PC(F,D-231-1)0000_0_dummy.sldprt",0,0,0)
posMat=createMat4x4FromValues(1,0,0,0,1,0,0,0,1,0,0,0)
swPosMat=createSWMatFromMat(posMat)
comp.SetXForm(swPosMat)
set comp=part.AddComponent2 ( storePath &"17000-0_rod_guide.sldprt",0,0,0)
posMat=createMat4x4FromValues(1,0,0,0,1,0,0,0,1,0,0,0)
swPosMat=createSWMatFromMat(posMat)
comp.SetXForm(swPosMat)
set comp=part.AddComponent2 ( storePath &"17-2_0432C.sldprt",0,0,0)
posMat=createMat4x4FromValues(1,0,0,0,1,0,0,0,1,0.0216408,0,0)
swPosMat=createSWMatFromMat(posMat)
comp.SetXForm(swPosMat)
set comp=part.AddComponent2 ( storePath &"17P0000_rear_head.sldprt",0,0,0)
posMat=createMat4x4FromValues(1,0,0,0,1,0,0,0,1,0.068199,0,0)
swPosMat=createSWMatFromMat(posMat)
comp.SetXForm(swPosMat)
set comp=part.AddComponent2 ( storePath &"D-358.sldprt",0,0,0)
posMat=createMat4x4FromValues(1,0,0,0,-1,0,0,0,-1,0.103124,0,0)
swPosMat=createSWMatFromMat(posMat)
comp.SetXForm(swPosMat)
set comp=part.AddComponent2 ( storePath &"C-170_5-P0_rod.sldprt",0,0,0)
posMat=createMat4x4FromValues(1,0,0,0,1,0,0,0,1,0,0,0)
swPosMat=createSWMatFromMat(posMat)
comp.SetXForm(swPosMat)
set comp=part.AddComponent2 ( storePath &"D-231-1-dummy.sldprt",0,0,0)
posMat=createMat4x4FromValues(1,0,0,0,1,0,0,0,1,-0.0452628,0,0)
swPosMat=createSWMatFromMat(posMat)
comp.SetXForm(swPosMat)
set comp=part.AddComponent2 ( storePath &"D-14053.sldprt",0,0,0)
posMat=createMat4x4FromValues(1,0,0,0,-1,0,0,0,-1,-0.0452628,0,0)
swPosMat=createSWMatFromMat(posMat)
comp.SetXForm(swPosMat)
set comp=part.AddComponent2 ( storePath &"D-8383.sldprt",0,0,0)
posMat=createMat4x4FromValues(0,0,1,0,1,0,-1,0,0,-0.0452628,0,0)
swPosMat=createSWMatFromMat(posMat)
comp.SetXForm(swPosMat)
set comp=part.AddComponent2 ( storePath &"D-5867.sldprt",0,0,0)
posMat=createMat4x4FromValues(-1,0,0,0,1,0,0,0,-1,-0.0452628,0,0.01010285)
swPosMat=createSWMatFromMat(posMat)
comp.SetXForm(swPosMat)
set comp=part.AddComponent2 ( storePath &"D-5867.sldprt",0,0,0)
posMat=createMat4x4FromValues(-1,0,0,0,1,0,0,0,-1,-0.0452628,0,-0.01010285)
swPosMat=createSWMatFromMat(posMat)
comp.SetXForm(swPosMat)
set comp=part.AddComponent2 ( storePath &"D-154.sldprt",0,0,0)
posMat=createMat4x4FromValues(0,0,1,0,1,0,-1,0,0,-0.011938,0,0)
swPosMat=createSWMatFromMat(posMat)
comp.SetXForm(swPosMat)
swApp.CloseDoc storePath &"170_5-PC(F,D-231-1)0000_0_dummy.sldprt"
swApp.CloseDoc storePath &"17000-0_rod_guide.sldprt"
swApp.CloseDoc storePath &"17-2_0432C.sldprt"
swApp.CloseDoc storePath &"17P0000_rear_head.sldprt"
swApp.CloseDoc storePath &"D-358.sldprt"
swApp.CloseDoc storePath &"C-170_5-P0_rod.sldprt"
swApp.CloseDoc storePath &"D-231-1-dummy.sldprt"
swApp.CloseDoc storePath &"D-14053.sldprt"
swApp.CloseDoc storePath &"D-8383.sldprt"
swApp.CloseDoc storePath &"D-5867.sldprt"
swApp.CloseDoc storePath &"D-5867.sldprt"
swApp.CloseDoc storePath &"D-154.sldprt"
part.EditRebuild3
part.Rebuild swRebuildAll
part.SaveAs2 storePath & "170_5-P(F,D-231-1).sldasm",0,0,false
end sub
sub codeBag0(part)
Part.InsertSketch
Set swActiveMat = Part.GetActiveSketch()
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,1,0,0,0,1,0,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
cLn part,wMat,0,0,0,0.00858901
cLn part,wMat,0,0.00858901,0.00093599,0.009525
cLn part,wMat,0.00093599,0.009525,0.0093100474613459,0.009525
cLn part,wMat,0.0093100474613459,0.009525,0.010262333186881,0.0086108210423271
cArc part,wMat,0.010262333186881,0.0086108210423271,0.010619173953759,0.0083802107542403,0.0110363,0.00829945
cLn part,wMat,0.0110363,0.00829945,0.0123698,0.00829945
cArc part,wMat,0.0123698,0.00829945,0.013160062538654,0.0086267874613459,0.0134874,0.00941705
cLn part,wMat,0.0134874,0.00941705,0.0134874,0.00949325
cLn part,wMat,0.0134874,0.00949325,0.015875,0.00949325
cLn part,wMat,0.015875,0.00949325,0.015875,0
cLn part,wMat,0.015875,0,0,0
cCLn part,wMat,0.015875,0,0,0
if (sw2007api=1) then
Part.SketchManager.InsertSketch True
else
Part.InsertSketch
End If
end sub

sub codeBag1(part)
Part.InsertSketch
Set swActiveMat = Part.GetActiveSketch()
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,1,0,0,0,1,0,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
cLn part,wMat,0.015875,0,0.015875,0.01976755
cLn part,wMat,0.015875,0.01976755,0.0206248,0.01976755
cLn part,wMat,0.0206248,0.01976755,0.0206248,0.01818005
cLn part,wMat,0.0206248,0.01818005,0.0216408,0.01818005
cLn part,wMat,0.0216408,0.01818005,0.0226568,0.01919605
cLn part,wMat,0.0226568,0.01919605,0.0262128,0.01919605
cLn part,wMat,0.0262128,0.01919605,0.0269748,0.01843405
cLn part,wMat,0.0269748,0.01843405,0.0269748,0
cLn part,wMat,0.0269748,0,0.015875,0
cCLn part,wMat,0.0269748,0,0.015875,0
if (sw2007api=1) then
Part.SketchManager.InsertSketch True
else
Part.InsertSketch
End If
end sub

sub codeBag2(part)
Part.InsertSketch
Set swActiveMat = Part.GetActiveSketch()
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,1,0,0,0,1,0,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
cLn part,wMat,0.0269748,0,0.0269748,0.0103124
cLn part,wMat,0.0269748,0.0103124,0.0325628,0.0103124
cLn part,wMat,0.0325628,0.0103124,0.0333248,0.0095504
cLn part,wMat,0.0333248,0.0095504,0.0333248,0
cLn part,wMat,0.0333248,0,0.0269748,0
cCLn part,wMat,0.0333248,0,0.0269748,0
if (sw2007api=1) then
Part.SketchManager.InsertSketch True
else
Part.InsertSketch
End If
end sub

sub codeBag3(part)
Part.InsertSketch
Set swActiveMat = Part.GetActiveSketch()
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,1,0,0,0,1,0,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
cLn part,wMat,0,0,0,0.0063754
cLn part,wMat,0,0.0063754,0.000762,0.0056134
cLn part,wMat,0.000762,0.0056134,0.0333248,0.0056134
cLn part,wMat,0.0333248,0.0056134,0.0333248,0
cLn part,wMat,0.0333248,0,0,0
cCLn part,wMat,0.0333248,0,0,0
if (sw2007api=1) then
Part.SketchManager.InsertSketch True
else
Part.InsertSketch
End If
end sub

sub codeBag4(part)
Part.InsertSketch
Set swActiveMat = Part.GetActiveSketch()
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,1,0,0,0,1,0,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
cLn part,wMat,0.0206248,0.01792605,0.0216408,0.01792605
cLn part,wMat,0.0216408,0.01792605,0.0216408,0.01818005
cLn part,wMat,0.0216408,0.01818005,0.0211328,0.01818005
cLn part,wMat,0.0211328,0.01818005,0.020758182071525,0.018554667928475
cArc part,wMat,0.020758182071525,0.018554667928475,0.020720984632736,0.018644470489686,0.020758182071525,0.018734273050896
cLn part,wMat,0.020758182071525,0.018734273050896,0.021707290824755,0.019683381804126
cLn part,wMat,0.021707290824755,0.019683381804126,0.021707290824755,0.01976755
cLn part,wMat,0.021707290824755,0.01976755,0.021504090824755,0.01976755
cLn part,wMat,0.021504090824755,0.01976755,0.0206248,0.018888259175245
cLn part,wMat,0.0206248,0.018888259175245,0.0206248,0.01792605
cCLn part,wMat,0.0216408,0,0.0206248,0
if (sw2007api=1) then
Part.SketchManager.InsertSketch True
else
Part.InsertSketch
End If
end sub

sub codeBag5(part)
Part.InsertSketch
Set swActiveMat = Part.GetActiveSketch()
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,1,0,0,0,1,0,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
cArc part,wMat,-0.00088261792847484,0.018734273050896,-0.00091981536726415,0.018644470489686,-0.00088261792847484,0.018554667928475
cLn part,wMat,-0.00088261792847484,0.018554667928475,-0.000508,0.01818005
cLn part,wMat,-0.000508,0.01818005,-7.0499162063697e-19,0.01818005
cLn part,wMat,-7.0499162063697e-19,0.01818005,0.001016,0.01919605
cLn part,wMat,0.001016,0.01919605,0.0508762,0.01919605
cLn part,wMat,0.0508762,0.01919605,0.0518922,0.01818005
cLn part,wMat,0.0518922,0.01818005,0.0524002,0.01818005
cLn part,wMat,0.0524002,0.01818005,0.052774817928475,0.018554667928475
cArc part,wMat,0.052774817928475,0.018554667928475,0.052812015367264,0.018644470489686,0.052774817928475,0.018734273050896
cLn part,wMat,0.052774817928475,0.018734273050896,0.052039120489686,0.019469970489686
cArc part,wMat,0.052039120489686,0.019469970489686,0.051709506367283,0.019690211605031,0.0513207,0.01976755
cLn part,wMat,0.0513207,0.01976755,0.0005715,0.01976755
cArc part,wMat,0.0005715,0.01976755,0.00018269363271707,0.019690211605031,-0.00014692048968553,0.019469970489686
cLn part,wMat,-0.00014692048968553,0.019469970489686,-0.00088261792847484,0.018734273050896
cCLn part,wMat,0.0518922,0,0,0
if (sw2007api=1) then
Part.SketchManager.InsertSketch True
else
Part.InsertSketch
End If
end sub

sub codeBag6(part)
Part.InsertSketch
Set swActiveMat = Part.GetActiveSketch()
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,1,0,0,0,1,0,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
cCir part,wMat,0.008509,0,0.0015875
if (sw2007api=1) then
Part.SketchManager.InsertSketch True
else
Part.InsertSketch
End If
end sub

sub codeBag7(part)
Part.InsertSketch
Set swActiveMat = Part.GetActiveSketch()
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,1,0,0,0,1,0,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
cLn part,wMat,0,0,0,0.01843405
cLn part,wMat,0,0.01843405,0.000762,0.01919605
cLn part,wMat,0.000762,0.01919605,0.004318,0.01919605
cLn part,wMat,0.004318,0.01919605,0.005334,0.01818005
cLn part,wMat,0.005334,0.01818005,0.00635,0.01818005
cLn part,wMat,0.00635,0.01818005,0.00635,0.01976755
cLn part,wMat,0.00635,0.01976755,0.021463,0.01976755
cLn part,wMat,0.021463,0.01976755,0.022225,0.01900555
cLn part,wMat,0.022225,0.01900555,0.022225,0
cLn part,wMat,0.022225,0,0,0
cCLn part,wMat,0.022225,0,0,0
if (sw2007api=1) then
Part.SketchManager.InsertSketch True
else
Part.InsertSketch
End If
end sub

sub codeBag8(part)
Part.InsertSketch
Set swActiveMat = Part.GetActiveSketch()
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,1,0,0,0,1,0,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
cLn part,wMat,0.022225,0,0.022225,0.0127
cLn part,wMat,0.022225,0.0127,0.042926,0.0127
cLn part,wMat,0.042926,0.0127,0.04445,0.011176
cLn part,wMat,0.04445,0.011176,0.04445,0
cLn part,wMat,0.04445,0,0.022225,0
cCLn part,wMat,0.04445,0,0.022225,0
if (sw2007api=1) then
Part.SketchManager.InsertSketch True
else
Part.InsertSketch
End If
end sub

sub codeBag9(part)
Part.InsertSketch
Set swActiveMat = Part.GetActiveSketch()
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(0,0,-1,0,1,0,1,0,0,0.04445,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
cLn part,wMat,-0.0395351,-0.0790702,0.0395351,-0.0790702
cLn part,wMat,0.0395351,-0.0790702,0.0395351,0.0790702
cLn part,wMat,0.0395351,0.0790702,-0.0395351,0.0790702
cLn part,wMat,-0.0395351,0.0790702,-0.0395351,-0.0790702
cLn part,wMat,-0.0078359,-0.0395351,0.0078359,-0.0395351
cLn part,wMat,0.0078359,-0.0395351,0.0078359,0.0395351
cLn part,wMat,0.0078359,0.0395351,-0.0078359,0.0395351
cLn part,wMat,-0.0078359,0.0395351,-0.0078359,-0.0395351
if (sw2007api=1) then
Part.SketchManager.InsertSketch True
else
Part.InsertSketch
End If
end sub

sub codeBag10(part)
Part.InsertSketch
Set swActiveMat = Part.GetActiveSketch()
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,1,0,0,0,1,0,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
cLn part,wMat,0,0,0,0.0067564
cLn part,wMat,0,0.0067564,0.02045208,0.0067564
cLn part,wMat,0.02045208,0.0067564,0.024352889358753,0
cLn part,wMat,0.024352889358753,0,0,0
cCLn part,wMat,0.024352889358753,0,0,0
if (sw2007api=1) then
Part.SketchManager.InsertSketch True
else
Part.InsertSketch
End If
end sub

sub codeBag11(part)
Part.InsertSketch
Set swActiveMat = Part.GetActiveSketch()
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,0.017452406437284,-0.99984769515639,0,0.99984769515639,0.017452406437284,0,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
cLn part,wMat,0.0142748,0,0.018897793377836,0
cLn part,wMat,0.018897793377836,0,0.018897793377836,-0.01283335
cLn part,wMat,0.018897793377836,-0.01283335,0.01911427592515,-0.01976755
cLn part,wMat,0.01911427592515,-0.01976755,0.0142748,-0.01976755
cLn part,wMat,0.0142748,-0.01976755,0.0142748,0
cCLn part,wMat,0.0142748,-0.01976755,0.0142748,0
if (sw2007api=1) then
Part.SketchManager.InsertSketch True
else
Part.InsertSketch
End If
end sub

sub codeBag12(part)
Part.InsertSketch
Set swActiveMat = Part.GetActiveSketch()
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,1,0,0,0,1,0,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
cLn part,wMat,0,0,0,0.0123063
cLn part,wMat,0,0.0123063,0.00635,0.0123063
cLn part,wMat,0.00635,0.0123063,0.00635,0
cLn part,wMat,0.00635,0,0,0
cCLn part,wMat,0.00635,0,0,0
if (sw2007api=1) then
Part.SketchManager.InsertSketch True
else
Part.InsertSketch
End If
end sub

sub codeBag13(part)
Part.InsertSketch
Set swActiveMat = Part.GetActiveSketch()
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,1,0,0,0,1,0,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
cLn part,wMat,0.0052675091752453,0.019683381804126,0.0062166179284748,0.018734273050896
cArc part,wMat,0.0062166179284748,0.018734273050896,0.0062538153672641,0.018644470489686,0.0062166179284748,0.018554667928475
cLn part,wMat,0.0062166179284748,0.018554667928475,0.005842,0.01818005
cLn part,wMat,0.005842,0.01818005,0.005334,0.01818005
cLn part,wMat,0.005334,0.01818005,0.005334,0.01792605
cLn part,wMat,0.005334,0.01792605,0.00635,0.01792605
cLn part,wMat,0.00635,0.01792605,0.00635,0.018888259175245
cLn part,wMat,0.00635,0.018888259175245,0.0054707091752453,0.01976755
cLn part,wMat,0.0054707091752453,0.01976755,0.0052675091752453,0.01976755
cLn part,wMat,0.0052675091752453,0.01976755,0.0052675091752453,0.019683381804126
cCLn part,wMat,0.0063500000000002,7.0499162063697e-17,0.0053340000000002,5.9219296133506e-17
if (sw2007api=1) then
Part.SketchManager.InsertSketch True
else
Part.InsertSketch
End If
end sub

sub codeBag14(part)
Part.InsertSketch
Set swActiveMat = Part.GetActiveSketch()
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,1,0,0,0,1,0,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
cCir part,wMat,0.034925,0,0.00479425
if (sw2007api=1) then
Part.SketchManager.InsertSketch True
else
Part.InsertSketch
End If
end sub

sub codeBag15(part)
Part.InsertSketch
Set swActiveMat = Part.GetActiveSketch()
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(0,0,-1,0,1,0,1,0,0,0,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
cLn part,wMat,-0.0127,0,-0.0127,0.0045110528286101
cLn part,wMat,-0.0127,0.0045110528286101,-0.01244855282861,0.0047625
cLn part,wMat,-0.01244855282861,0.0047625,0.0123444,0.0047625
cLn part,wMat,0.0123444,0.0047625,0.0127,0.0044069
cLn part,wMat,0.0127,0.0044069,0.0127,0
cLn part,wMat,0.0127,0,-0.0127,0
cCLn part,wMat,0.0127,0,-0.0127,0
if (sw2007api=1) then
Part.SketchManager.InsertSketch True
else
Part.InsertSketch
End If
end sub

sub codeBag16(part)
Part.InsertSketch
Set swActiveMat = Part.GetActiveSketch()
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,1,0,0,0,1,0,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
cLn part,wMat,-0.00635,0,-0.00635,0.0055499
cLn part,wMat,-0.00635,0.0055499,0.0460248,0.0055499
cLn part,wMat,0.0460248,0.0055499,0.0460248,0.01914525
cLn part,wMat,0.0460248,0.01914525,0.068199,0.01914525
cLn part,wMat,0.068199,0.01914525,0.068199,0
cLn part,wMat,0.068199,0,-0.00635,0
cCLn part,wMat,0.068199,0,-0.00635,0
if (sw2007api=1) then
Part.SketchManager.InsertSketch True
else
Part.InsertSketch
End If
end sub

sub codeBag17(part)
Part.InsertSketch
Set swActiveMat = Part.GetActiveSketch()
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,1,0,0,0,1,0,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
cLn part,wMat,-0.0254,0,-0.0254,0.0048006
cLn part,wMat,-0.0254,0.0048006,-0.02464435,0.00555625
cLn part,wMat,-0.02464435,0.00555625,-0.00635,0.00555625
cLn part,wMat,-0.00635,0.00555625,-0.00635,0
cLn part,wMat,-0.00635,0,-0.0254,0
cCLn part,wMat,-0.00635,0,-0.0254,0
if (sw2007api=1) then
Part.SketchManager.InsertSketch True
else
Part.InsertSketch
End If
end sub

sub codeBag18(part)
Part.InsertSketch
Set swActiveMat = Part.GetActiveSketch()
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(0,0,-1,0,1,0,1,0,0,-0.00635,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
cLn part,wMat,-0.0110998,0.0110998,-0.0110998,-0.0110998
cLn part,wMat,-0.0110998,-0.0110998,0.0110998,-0.0110998
cLn part,wMat,0.0110998,-0.0110998,0.0110998,0.0110998
cLn part,wMat,0.0110998,0.0110998,-0.0110998,0.0110998
cLn part,wMat,-0.004826,0.0055499,-0.004826,-0.0055499
cLn part,wMat,-0.004826,-0.0055499,0.004826,-0.0055499
cLn part,wMat,0.004826,-0.0055499,0.004826,0.0055499
cLn part,wMat,0.004826,0.0055499,-0.004826,0.0055499
if (sw2007api=1) then
Part.SketchManager.InsertSketch True
else
Part.InsertSketch
End If
end sub

sub codeBag19(part)
Part.InsertSketch
Set swActiveMat = Part.GetActiveSketch()
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,1,0,0,0,1,0,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
cLn part,wMat,-0.0095504,0.009525,-0.0095504,-0.009525
cLn part,wMat,-0.0095504,-0.009525,0.0333248,-0.009525
cLn part,wMat,0.0333248,-0.009525,0.0333248,0.009525
cLn part,wMat,0.0333248,0.009525,-0.0095504,0.009525
if (sw2007api=1) then
Part.SketchManager.InsertSketch True
else
Part.InsertSketch
End If
end sub

sub codeBag20(part)
Part.InsertSketch
Set swActiveMat = Part.GetActiveSketch()
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,0,-1,0,1,0,0,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
cLn part,wMat,-0.0095504,0.00492125,-0.0095504,-0.00492125
cLn part,wMat,-0.0095504,-0.00492125,0.0142748,-0.00492125
cLn part,wMat,0.0142748,-0.00492125,0.0142748,0.00492125
cLn part,wMat,0.0142748,0.00492125,-0.0095504,0.00492125
if (sw2007api=1) then
Part.SketchManager.InsertSketch True
else
Part.InsertSketch
End If
end sub

sub codeBag21(part)
Part.InsertSketch
Set swActiveMat = Part.GetActiveSketch()
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,1,0,0,0,1,0,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
cLn part,wMat,0.0175768,0,0.0175768,0.00486918
cLn part,wMat,0.0175768,0.00486918,0.03263773,0.00486918
cLn part,wMat,0.03263773,0.00486918,0.0333248,0.00555625
cLn part,wMat,0.0333248,0.00555625,0.0333248,0
cLn part,wMat,0.0333248,0,0.0175768,0
cCLn part,wMat,0.0333248,0,0.0175768,0
if (sw2007api=1) then
Part.SketchManager.InsertSketch True
else
Part.InsertSketch
End If
end sub

sub codeBag22(part)
Part.InsertSketch
Set swActiveMat = Part.GetActiveSketch()
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,1,0,0,0,1,0,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
cLn part,wMat,0.0142748,0,0.0142748,0.00496062
cLn part,wMat,0.0142748,0.00496062,0.0175768,0.00496062
cLn part,wMat,0.0175768,0.00496062,0.0175768,0
cLn part,wMat,0.0175768,0,0.0142748,0
cCLn part,wMat,0.0175768,0,0.0142748,0
if (sw2007api=1) then
Part.SketchManager.InsertSketch True
else
Part.InsertSketch
End If
end sub

sub codeBag23(part)
Part.InsertSketch
Set swActiveMat = Part.GetActiveSketch()
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(0,0,-1,0,1,0,1,0,0,0,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
cLn part,wMat,-0.009525,0,-0.009525,0.0058674
cLn part,wMat,-0.009525,0.0058674,-0.008382,0.0047244
cLn part,wMat,-0.008382,0.0047244,0.008382,0.0047244
cLn part,wMat,0.008382,0.0047244,0.009525,0.0058674
cLn part,wMat,0.009525,0.0058674,0.009525,0
cLn part,wMat,0.009525,0,-0.009525,0
cCLn part,wMat,0.009525,0,-0.009525,0
if (sw2007api=1) then
Part.SketchManager.InsertSketch True
else
Part.InsertSketch
End If
end sub

sub codeBag24(part)
Part.InsertSketch
Set swActiveMat = Part.GetActiveSketch()
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,1,0,0,0,1,0,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
cLn part,wMat,0.0333248,0,0.0333248,0.009525
cArc part,wMat,0.0333248,0.009525,0.032370901294441,0.014371793678518,0.0307848,0.01905
cLn part,wMat,0.0307848,0.01905,0.0428498,0.01905
cLn part,wMat,0.0428498,0.01905,0.0428498,0
cLn part,wMat,0.0428498,0,0.0333248,0
cCLn part,wMat,0.0428498,0,0.0333248,0
if (sw2007api=1) then
Part.SketchManager.InsertSketch True
else
Part.InsertSketch
End If
end sub

sub codeBag25(part)
Part.InsertSketch
Set swActiveMat = Part.GetActiveSketch()
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,1,0,0,0,1,0,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
cLn part,wMat,-0.0190754,0,-0.0190754,0.01905
cLn part,wMat,-0.0190754,0.01905,-0.0070104,0.01905
cArc part,wMat,-0.0070104,0.01905,-0.0085965012944413,0.014371793678518,-0.0095504,0.009525
cLn part,wMat,-0.0095504,0.009525,-0.0095504,0
cLn part,wMat,-0.0095504,0,-0.0190754,0
cCLn part,wMat,-0.0095504,0,-0.0190754,0
if (sw2007api=1) then
Part.SketchManager.InsertSketch True
else
Part.InsertSketch
End If
end sub

sub codeBag26(part)
Part.InsertSketch
Set swActiveMat = Part.GetActiveSketch()
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,1,0,0,0,1,0,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
cLn part,wMat,-0.0130937,0,-0.0130937,0.00440055
cLn part,wMat,-0.0130937,0.00440055,-0.0127127,0.00478155
cLn part,wMat,-0.0127127,0.00478155,-0.0106172,0.00478155
cLn part,wMat,-0.0106172,0.00478155,-0.0106172,0.00386715
cLn part,wMat,-0.0106172,0.00386715,-0.0095885,0.00386715
cLn part,wMat,-0.0095885,0.00386715,-0.0095885,0.00478155
cLn part,wMat,-0.0095885,0.00478155,0.0095885,0.00478155
cLn part,wMat,0.0095885,0.00478155,0.0095885,0.00386715
cLn part,wMat,0.0095885,0.00386715,0.0106172,0.00386715
cLn part,wMat,0.0106172,0.00386715,0.0106172,0.00478155
cLn part,wMat,0.0106172,0.00478155,0.0127127,0.00478155
cLn part,wMat,0.0127127,0.00478155,0.0130937,0.00440055
cLn part,wMat,0.0130937,0.00440055,0.0130937,0
cLn part,wMat,0.0130937,0,-0.0130937,0
cCLn part,wMat,0.0130937,0,-0.0130937,0
if (sw2007api=1) then
Part.SketchManager.InsertSketch True
else
Part.InsertSketch
End If
end sub

sub codeBag27(part)
Part.InsertSketch
Set swActiveMat = Part.GetActiveSketch()
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,1,0,0,0,1,0,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
cArc part,wMat,0.0060485443880461,-0.0073580388546022,3.2828140734729e-18,0.009525,-0.0060485444737582,-0.0073580387841441
cArc part,wMat,-0.0060485444737582,-0.0073580387841441,-0.0049583928226883,-0.0076413108794197,-0.004037371747189,-0.0069929329951745
cLn part,wMat,-0.004037371747189,-0.0069929329951745,-0.0022915935039836,-0.0039691563791944
cArc part,wMat,-0.0022915935039836,-0.0039691563791944,-0.0022000541492661,-0.0034445793628924,-0.0024687528202462,-0.0029848386493287
cArc part,wMat,-0.0024687528202462,-0.0029848386493287,-0.003354549401559,-0.00193675,-0.0038193225066394,-0.00064558333333333
cArc part,wMat,-0.0038193225066394,-0.00064558333333333,-0.0040831203082495,-0.00018301310151962,-0.0045831870079673,0
cLn part,wMat,-0.0045831870079673,0,-0.0057368949568415,0
cArc part,wMat,-0.0057368949568415,0,-0.006415354377335,0.00031223539657162,-0.006619494180971,0.0010306538461538
cArc part,wMat,-0.006619494180971,0.0010306538461538,-0.0058017206863029,0.003349625,-0.0042023195037628,0.0052173231978472
cArc part,wMat,-0.0042023195037628,0.0052173231978472,-0.0034780809740592,0.005399742166766,-0.0028684474784207,0.0049682967714676
cLn part,wMat,-0.0028684474784207,0.0049682967714676,-0.0022915935039836,0.0039691563791944
cArc part,wMat,-0.0022915935039836,0.0039691563791944,-0.0018830661589834,0.003627592464412,-0.0013505696449148,0.0036304219980926
cArc part,wMat,-0.0013505696449148,0.0036304219980926,1.4853122221159e-18,0.0038735,0.0013505696863932,0.003630421982662
cArc part,wMat,0.0013505696863932,0.003630421982662,0.0018830661589834,0.003627592464412,0.0022915935039836,0.0039691563791944
cLn part,wMat,0.0022915935039836,0.0039691563791944,0.0028684474784207,0.0049682967714676
cArc part,wMat,0.0028684474784207,0.0049682967714676,0.0034780809740592,0.005399742166766,0.0042023195037628,0.0052173231978472
cArc part,wMat,0.0042023195037628,0.0052173231978472,0.0058017206863029,0.003349625,0.006619494180971,0.0010306538461538
cArc part,wMat,0.006619494180971,0.0010306538461538,0.006415354377335,0.00031223539657162,0.0057368949568415,0
cLn part,wMat,0.0057368949568415,0,0.0045831870079673,0
cArc part,wMat,0.0045831870079673,0,0.0040831203082495,-0.00018301310151962,0.0038193225026968,-0.00064558335665806
cArc part,wMat,0.0038193225026968,-0.00064558335665806,0.003354549401559,-0.00193675,0.0024687528202462,-0.0029848386493287
cArc part,wMat,0.0024687528202462,-0.0029848386493287,0.0022000541492661,-0.0034445793628924,0.0022915935039836,-0.0039691563791944
cLn part,wMat,0.0022915935039836,-0.0039691563791944,0.004037371747189,-0.0069929329951745
cArc part,wMat,0.004037371747189,-0.0069929329951745,0.0049583928226883,-0.0076413108794197,0.0060485443880461,-0.0073580388546022
if (sw2007api=1) then
Part.SketchManager.InsertSketch True
else
Part.InsertSketch
End If
end sub

sub codeBag28(part)
Part.InsertSketch
Set swActiveMat = Part.GetActiveSketch()
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(0,0,-1,0,1,0,1,0,0,0,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
cLn part,wMat,0,0,0,0.008763
cLn part,wMat,0,0.008763,0.00046960775465478,0.0105156
cLn part,wMat,0.00046960775465478,0.0105156,0.0058803922453452,0.0105156
cLn part,wMat,0.0058803922453452,0.0105156,0.00635,0.008763
cLn part,wMat,0.00635,0.008763,0.00635,0
cLn part,wMat,0.00635,0,0,0
cCLn part,wMat,0.00635,0,0,0
if (sw2007api=1) then
Part.SketchManager.InsertSketch True
else
Part.InsertSketch
End If
end sub

sub codeBag29(part)
Part.InsertSketch
Set swActiveMat = Part.GetActiveSketch()
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,1,0,0,0,1,0,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
cLn part,wMat,-0.017526,0.017526,-0.017526,-0.017526
cLn part,wMat,-0.017526,-0.017526,0.017526,-0.017526
cLn part,wMat,0.017526,-0.017526,0.017526,0.017526
cLn part,wMat,0.017526,0.017526,-0.017526,0.017526
cLn part,wMat,-0.008763,0.0050593204089087,-0.008763,-0.0050593204089087
cLn part,wMat,-0.008763,-0.0050593204089087,0,-0.010118640817817
cLn part,wMat,0,-0.010118640817817,0.008763,-0.0050593204089087
cLn part,wMat,0.008763,-0.0050593204089087,0.008763,0.0050593204089087
cLn part,wMat,0.008763,0.0050593204089087,0,0.010118640817817
cLn part,wMat,0,0.010118640817817,-0.008763,0.0050593204089087
if (sw2007api=1) then
Part.SketchManager.InsertSketch True
else
Part.InsertSketch
End If
end sub

sub codeBag30(part)
Part.InsertSketch
Set swActiveMat = Part.GetActiveSketch()
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(0,0,-1,0,1,0,1,0,0,0,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
cLn part,wMat,0,0,0,0.00555625
cLn part,wMat,0,0.00555625,0.00068707,0.00486918
cLn part,wMat,0.00068707,0.00486918,0.00566293,0.00486918
cLn part,wMat,0.00566293,0.00486918,0.00635,0.00555625
cLn part,wMat,0.00635,0.00555625,0.00635,0
cLn part,wMat,0.00635,0,0,0
cCLn part,wMat,0.00635,0,0,0
if (sw2007api=1) then
Part.SketchManager.InsertSketch True
else
Part.InsertSketch
End If
end sub

sub main
set swApp = Application.SldWorks
code = swApp.RevisionNumber
found = InStr(code, ".")
If (found > 0) Then
  code = Left(code, found-1)
  If (CInt(code) >= 11) Then
    sw2003api=1
  End If
  If (CInt(code) >= 15) Then
    sw2007api=1
  End If
  docVisible=1
  If (CInt(code) >= 18) Then
    docVisible=0
  End If
End If
swApp.SetUserPreferenceToggle 11, FALSE
swApp.SetUserPreferenceToggle 97, FALSE
storePath=BrowseForFolder
If (storePath <> "") Then
   If ((Right(storePath, 1) <> "\") And (Right(storePath, 1) <> "/")) Then
       storePath = storePath + "\"
   End If
   createPart11
End If
end sub
